mana-ethereum/mana

apps/evm/mix.exs
What changed?
============
The `evm` app has a typo in its mix dependencies. As such, we cannot pull dependencies.
=> Fix in_umbrella typo

README.md
What changed?
=============
Adds some basic instructions on how to setup project. A couple of things worth highlighting:
- Ran into issues because `automake` wasn't installed. Thus, I have included a `Requirements` section. But since this section does not include all requirements, maybe we should remove it or augment it. I include it here, but I'm happy to remove it if it doesn't make sense to include it.
- Added a command to clone repo with submodules. This is helpful to know in order to be able to run the shared ethereum tests.
=> Adds instructions to setup in README

.gitignore
We add `_lexer.erl` and `_parser.erl` files to `.gitignore` because they are generated from `yecc` and `leex` (from the `abi` app). When merging the different repositories under a single umbrella, it seems like this was forgotten.
=> Ignore _lexer.erl and _parser.erl files

.circleci/config.yml, apps/blockchain/lib/blockchain/block.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/lib/eth_common_test/harness.ex, apps/blockchain/lib/eth_common_test/helpers.ex, apps/blockchain/test/blockchain/block_test.exs, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain/transaction_test.exs, apps/evm/lib/evm/operation/system.ex
The problem was [hitting 4G memory limit](https://circleci.com/docs/1.0/oom/) on CircleCI.
`String10MbData` test eats memory heap so it takes more than allowed 4GB.
To prevent this I've set max_heap_size to 4095 mb (see `.circleci/config.yml` config for details).
My solution is to:
1. Set the default maximum heap size to 4095 for test env (to prevent process killing).
2. Ignore the `String10MbData` test for now.
3. Create a ticket to find out whats wrong later (see the [#23](https://waffle.io/poanetwork/mana/cards/5af074b1dcbe45001be58757) in Waffle)
More info:
* http://erlang.org/doc/man/erl.html (for `hmax` CLI option).
=> Gv fix blockchain test

apps/blockchain/lib/eth_common_test/helpers.ex, apps/blockchain/test/blockchain/transaction_test.exs
This work is part of #10 -- making all ethereum common tests pass in the blockchain project.
What changed?
===============
According to the [EIP155 specification](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md), a chain_id is used when signing the transaction. So any chains after the EIP155 fork need to include that chain id when signing the transaction.
The implementation code already handles that. But the tests were ignoring any common tests that had a `v` value greater than `30`. We fix that here by passing the `mainnet`'s `chain_id` of `1` for any chains that came after EIP155.
Because we now handle that, the logic for all common tests generated from the `TransactionTests` directory can be combined into a single use of `define_common_tests/3` (note we continue to ignore …
=> Add chain_id for blockchain tests that need it

apps/blockchain/lib/eth_common_test/harness.ex, apps/blockchain/test/blockchain/block_test.exs
This is part of the work for #10 -- making all ethereum common tests pass for the blockchain app
What changed?
============
Block tests were the last to use the `eth_test/2` macro in `EthCommmonTest.Harness`. We update this code to use `define_common_test/3` instead and we remove `eth_test/2`
Note that `define_common_test/3` and `eth_test/2` are not exactly one to one. Since each file under `ethereum_common_test` has a different json structure, we have opted to use `define_common_test/3` which simply loads the tests by file name and provides the data in the test as a map.
That means that each elixir test (like `block_test.exs`) needs to define how to implement a test for each of the "sub-tests" defined within a common test file. For example, `GenesisTests/basic_genesis_test.json` defines …
=> Use define_common_test/3 instead of eth_test/2

apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/block.ex
Fixes some of the dialyzer warnings for the  Blockchain app.
Warning fixed is included in each commit message.
This is the 1st PR, not all the warnings are gone yet.
An extra commit included which removes the unused `identity()` function.
=> Dialyzer warning fixes PR#1

.dialyzer.ignore-warnings, mix.exs
We don't ignore the whole Blockchain app anymore, only specific warnings to be ignored are added to `.dialyzer.ignore-warnings`
Ignore file now includes full EVM file paths, not specific warnings. This is because the lines where the warnings comes from might change when code is being updated which means the CI would fail.
Note: Merge after https://github.com/poanetwork/mana/pull/79
=> Ignore specific Blockchain app warnings

.circleci/config.yml, apps/blockchain/test/blockchain/transaction_test.exs
* Remove max heap size limit for test env
* Stop ignoring String10MbData test (ttData/String10MbData.json)
As we've moved to the paid plan on CircleCI, this is not an issue anymore.
=> Stop ignoring String10MbData test

.circleci/config.yml
cargo directories  weren't cached for dialyzer:
```
#!/bin/bash -eo pipefail
mix dialyzer --plt
==> rustler
Compiling 2 files (.erl)
Compiling 6 files (.ex)
Generated rustler app
==> rox
Compiling NIF crate :rox_nif (native/rox_nif)...
Updating registry `https://github.com/rust-lang/crates.io-index`
Updating git repository `https://github.com/urbint/rust-rocksdb.git`
Downloading rustler v0.15.1
Downloading lazy_static v0.2.8
Downloading rustler_codegen v0.15.1
Downloading lazy_static v0.1.16
Downloading erlang_nif-sys v0.6.3
Downloading unreachable v0.1.1
Downloading void v1.0.2
...
```
=> add cargo directories for dialyzer ci cache

README.md
Since we added [rox](https://github.com/urbint/rox) and since `rox` needs Rust to be available at compile time, we include that requirement to the README. Without it, we cannot succesfully compile dependencies for `mana`.
=> Add Rust requirement to README

apps/evm/lib/evm/builtin.ex, apps/evm/test/evm/builtin_test.exs
Implements `run_sha256` function which is one of the builtin contracts.
It runs SHA2-256 hashing.
The usage of gas depends on the data size.
The input comes from execution environment attribute `data`.
The output is the hash, unless there isn't enough gas.
=> Precompiled Contract: SHA2-256

apps/ex_wire/lib/ex_wire/adapter/tcp/server.ex, apps/ex_wire/lib/ex_wire/handshake/eip_8.ex, apps/ex_wire/lib/ex_wire/handshake/handshake.ex, apps/ex_wire/test/ex_wire/handshake/handshake_test.exs
While doing work for https://github.com/poanetwork/mana/issues/103, I discovered the following:
There were several functions that were taking the peer's host as an argument solely so they could print it in a `Logger` call. This seems unnecessary since we should only pass the things that are needed to the functions.
It was also confusing since (a) it made it seem like functions needed to know about the peer when they didn't, and (b) it adds a lot of misleading noise when running tests -- logging that something is being sent over the network when in fact only a struct is being built.
=> Do not pass unneeded peer's uri host as argument

apps/evm/lib/evm/builtin.ex
Implements `run_rip160` function which is one of the builtin contracts.
The usage of gas depends on the data size.
As `ripmed160` hashing returns 20 bytes, we need to pad the result so the output is 32 bytes.
=> Precompiled Contract: ripmed160

apps/ex_wire/lib/ex_wire/framing/secrets.ex, apps/ex_wire/lib/ex_wire/handshake/handshake.ex, apps/ex_wire/test/ex_wire/framing/secrets_test.exs
Summary
=======
The `Secrets.derive_secrets/7` function was throwing an `ArgumentError` when trying to generate a shared secret. It was untested and for all intents an purposes, it was unused. So the bug was never caught. As part of my work on #103, I realized that this function was causing issues when trying to derive secrets for the encrypted auth exchange. 
The function failed when trying to generate an ephemeral shared secret. In order to generate that shared secret, we need our node's ephemeral private key and the remote node's ephemeral public key.
The function was trying to pass a "raw" ephemeral public key instead. And when looked at closely, it wasn't even passing the correct "raw" key. Instead it was using a function that transformed the `remote_ephemeral_public_key` from raw …
=> Fix Secrets.derive_secrets/7 function

apps/ex_wire/config/test.exs, apps/ex_wire/test/ex_wire_test.exs
Node Discovery uses two processes: Network process sends async request and receives requests from other nodes and redirects them to Kademlia process, Kademlia stores routing table(buckets, etc) and sends requests (ping, pong, find_neighbours) using network process. Network process can use different adapters, Test adapter is used for tests (wire_test.exs is the only place that it's used) (edited)
adapters respond to different GenServer callbacks.  Kademlia process tries to use test adapter to send requests and test adapter fails. We start production adapter manually when we need it in tests. 
Let's start Test adapter only for `ExWireTest `
fixes https://github.com/poanetwork/mana/issues/123
=> fix network adapter for ex_wire test

apps/evm/lib/evm/exec_env.ex, apps/evm/lib/evm/machine_state.ex, apps/evm/lib/evm/operation.ex, apps/evm/lib/evm/operation/environmental_information.ex, apps/evm/lib/evm/operation/metadata/environmental_information.ex, apps/evm/lib/evm/vm.ex
- add `last_return_data` field to `machineState` struct to track last op output data
- implement `RETURNDATASIZE`
Part of https://github.com/poanetwork/mana/issues/131
=>  implement RETURNDATASIZE env op 

apps/ex_wire/lib/ex_wire/handshake/struct/ack_resp_v4.ex, apps/ex_wire/test/ex_wire/handshake/handshake_test.exs
This issue was discovered while working on https://github.com/poanetwork/mana/issues/103, but it can be committed separately from the rest of the work.
Summary
=======
The AckRespV4 struct is slightly different than the AuthMsgV4 struct. The latter manipulates the keys when serializing and deserializing them, turning them from `raw` to `der` and viceversa.
This subtle difference presents a problem in other places when we expect those keys to be of similar type (either raw or der). For example, the `Secrets.derive_secrets` can be used when receiving and auth message or an ack message.
For those reason, we make AckRespV4 behave like AuthMsgV4, making the key `raw` when serializing to be sent to our peers, and making it `der` when deserializing the data received from a peer.
=> Make AckRespV4 behave the same as AuthMsgV4

apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/evm/README.md, apps/evm/lib/evm/address.ex, apps/evm/lib/evm/debugger/breakpoint.ex, apps/evm/lib/evm/exec_env.ex, apps/evm/lib/evm/functions.ex, apps/evm/lib/evm/gas.ex, apps/evm/lib/evm/interface/account_interface.ex, apps/evm/lib/evm/interface/mock/mock_account_interface.ex, apps/evm/lib/evm/machine_code.ex, apps/evm/lib/evm/machine_state.ex, apps/evm/lib/evm/operation.ex, apps/evm/lib/evm/operation/logging.ex, apps/evm/lib/evm/operation/metadata/system.ex, apps/evm/lib/evm/operation/push.ex, apps/evm/lib/evm/operation/system.ex, apps/evm/lib/evm/sub_state.ex, apps/evm/lib/evm/vm.ex, apps/evm/test/evm/operation/system_test.exs, apps/evm/test/evm/vm_test.exs, apps/evm/test/evm_test.exs, apps/exth_crypto/lib/math.ex
* Rename `suicide` op to `selfdestruct` according to [EIP-6](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6.md).
* Transfer the balance of the self-destructed account to the "refund account" (its address is the top 20-bytes on VM's stack). Refund account is "shadow-created" if it doesn't exist.
* Refactor and fix the `evm_test.exs`:
* Remove the `code` field from the caller's account (see http://ethereum-tests.readthedocs.io/en/latest/test_types/vm_tests.html#the-exec-section).
* Exclude caller's account from the actual state if it isn't in the "pre" or "post" addresses.
* Don't ignore empty state values in EVM tests.
* Update `EVM.Address.new` to use only the last `@size` of bytes for address construction:
this is important because in VM operations we're getting addresses from …
=> Fix EVM tests

apps/evm/lib/evm/operation/stack_memory_storage_and_flow.ex, apps/evm/test/evm/operation/stack_memory_storage_and_flow_test.exs
https://github.com/poanetwork/mana/issues/133
I was confused by the comment in doctests so I thought this operation wasn't implemented.
Actually, the last stack value is being popped when operation arguments are taken from the stack.
=> add test for pop, remove comment

.circleci/config.yml, apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/blocktree.ex, apps/ex_wire/lib/ex_wire/kademlia/routing_table.ex, apps/ex_wire/lib/ex_wire/network.ex, apps/ex_wire/lib/ex_wire/sync.ex, apps/ex_wire/test/ex_wire_test.exs, apps/merkle_patricia_tree/lib/db/rocksdb.ex, apps/merkle_patricia_tree/lib/trie/storage.ex
Elixir Docker Image
====================
Use elixir 1.6.4 in CircleCI
Our builds started failing across several branches. Looking at the builds, I noticed that the sha for the elixir docker image (circleci/elixir:1.6) had changed when the builds started working.
Part of the error messages was,
```
mandatory chunk of type 'Atom' not found
```
A quick search revealed that the error is commonly found when compiling code in a newer version of Erlang/OTP and running it in an older version (e.g. compiling it in Erlang/OTP 20 and running it in Erlang/OTP 19).
By ssh'ing into CircleCI, I was able to see that we were running Elixir 1.6.5 compiled in Erlang/OTP 19 and we were running in Erlang/OTP 19.
Since we're running in the same version of Erlang as we compiled, I don't know why we're seeing …
=> Fix CI build

apps/ex_wire/lib/ex_wire/handshake/handshake.ex, apps/ex_wire/lib/ex_wire/handshake/struct/auth_msg_v4.ex, apps/ex_wire/test/ex_wire/handshake/struct/auth_msg_v4_test.exs, apps/exth_crypto/lib/signature.ex, apps/exth_crypto/test/signature_test.exs
During our work for https://github.com/poanetwork/mana/issues/103, we discovered some tests that fail intermittently. This fixes those issues.
Summary
========
`ExthCrypto.Signature.sign_digest/2` returns a `signature` and a `recovery_id`. We then concatenate those two when creating the `AuthMsgV4` struct. When the recipient tries to recover the public key, however, we are hardcoding the `recovery_id` to `0`. This led to intermittent failures in our tests (when the recover_id != 0).
To properly handle this, we create two functions in `ExthCrypto.Signature` to create a compact signature (sig + recover_id) and to split that compact signature when recovering it.
Using those functions, we fix the bug by no longer hardcoding the `0` but retrieving the correct recovery id from the auth message, …
=> Fix Signature recovery in crypto handshake

apps/ex_wire/lib/ex_wire/handshake/handshake.ex, apps/ex_wire/lib/ex_wire/handshake/struct/ack_resp_v4.ex, apps/ex_wire/lib/ex_wire/handshake/struct/auth_msg_v4.ex, apps/ex_wire/test/ex_wire/handshake/handshake_test.exs, apps/ex_wire/test/ex_wire/handshake/struct/auth_msg_v4_test.exs
This is done as part of supporting https://github.com/poanetwork/mana/issues/103.
Why this change?
================
The keys in `AuthMsgV4` and `AckRespV4` are all defined as `remote_*`. But they can be more accurately named `initiator_*` and `recipient_*`. Having them named `remote_*` leaves ambiguity since which peer is the remote peer is dependent on which node we are currently talking about. That creates confusion.
The most concrete example of this confusion is `auth_msg.remote_ephemeral_public_key`. When the initiator sends an auth message, that key will be `nil`. When the recipient receives the message, they will fill in the `remote_ephemeral_public_key` with the initiator's public key because the remote is the initiator from their perspective.
This naming also more closely matches …
=> Change AuthMsgV4 and AckRespV4 keys

apps/ex_wire/lib/ex_wire/adapter/tcp.ex, apps/ex_wire/lib/ex_wire/adapter/tcp/server.ex, apps/ex_wire/lib/ex_wire/handshake.ex, apps/ex_wire/test/ex_wire/handshake_test.exs, apps/exth_crypto/lib/ecies/ecdh.ex
Summary
=======
This commit handles two things that are interrelated. It adds a naive implementation for an inbound TCP connection and fixes the function that handles the main crypto handshake when it is initiated by the remote peer. This is all part of supporting #103.
Fix inbound handshake
=====================
The main function that was called when a remote node initiated the handshake (sending an auth message) was `Handshake.try_handle_auth/4`.
`Handshake.try_handle_auth/4`, however, was broken. It had an unrealistic function signatures (assuming we would have peer data that we can only obtain after decrypting auth message). It also called `Handshake.build_ack_resp/2` incorrectly, passing incorrect argument types and values. This function was untested and practically unused, so the …
=> Fix inbound handshake & add naive TCP inbound implementation

apps/ex_wire/lib/ex_wire/adapter/tcp/server.ex, apps/ex_wire/lib/ex_wire/handshake.ex, apps/ex_wire/lib/ex_wire/tcp.ex, apps/ex_wire/test/ex_wire/handshake_test.exs
While we were doing work for inbound messaging, we improved `Handshake.handle_auth`, but we left `Handshake.try_handle_ack` so as to not introduce too much noise into the commits.
Here we do some clean up of that function (renaming it, and improving the function signature), and we clean up the TCP.Server module which calls those functions. We also extract `:gen_tcp` functions and reduce the number of messages the server request of itself.
=> Improve Handshake.handle_ack/2 and TCP.Server

apps/ex_wire/lib/ex_wire/adapter/tcp/server.ex, apps/ex_wire/lib/ex_wire/crypto.ex, apps/ex_wire/lib/ex_wire/handshake.ex, apps/ex_wire/lib/ex_wire/handshake/struct/auth_msg_v4.ex, apps/ex_wire/lib/ex_wire/struct/peer.ex, apps/ex_wire/lib/ex_wire/tcp.ex, apps/ex_wire/test/ex_wire/handshake_test.exs, apps/exth_crypto/lib/signature.ex
Summary
=======
We retrieve peer data and construct a `%Peer{}` struct for inbound TCP connections. For outgoing connections, this is much easier because we know which peer we're connecting to. For the inbound connection, it was a little more difficult.
For background information, the [enode url](https://github.com/ethereum/wiki/wiki/enode-url-format) looks like this:
```
enode://hex_node_id@ip_address:port
```
We retrieve the host (ip address) and port peer data from the socket connection using `:inet.peername/1`, and we retrieve the peer's public id from decoding the auth message the peer first sends.
Since we can now do that, we can construct a `Peer` struct for all inbound TCP connections, and we normalize the Logger messages and function signatures.
The only place where we continue …
=> Add peer struct to inbound TCP.Server

apps/blockchain/test/blockchain/state_test.exs, apps/evm/lib/evm/operation/system.ex
Stackdepth was incremented 2 times in callcode operation
=> fix stackdepth incrementation for callcode operations

apps/ex_wire/lib/ex_wire/adapter/tcp/server.ex, apps/ex_wire/lib/ex_wire/framing/secrets.ex, apps/ex_wire/lib/ex_wire/handshake.ex, apps/ex_wire/test/ex_wire/framing/secrets_test.exs, apps/ex_wire/test/integration/dev_p2p_communication_test.exs
This adds the first part of https://github.com/poanetwork/mana/issues/166, sending `Hello` messages. After this, we should confirm we can send all the DEVp2p protocol messages (and receive them), and we should set the devp2p session as active when the Hello messages have been exchanged.
Summary
=======
Since we now have the encrypted handshake complete, we move on to make sure the DEVp2p protocol handshake (sending `Hello` messages) is exchanged. To this end, we initialize a DEVp2p session and send a Hello message. We also add an integration test to ensure that we're performing the exchanges successfully. The test is a little odd because our assertions are obtained through tracing the messages going through the processes. There may be better ways to test this (say if we do a lot of …
=> Add DEVp2p Handshake and fix secrets

apps/blockchain/scripts/generate_state_tests.ex
Count tests that `throw` and are `rescued` as failing tests
=> Fix failing test count in general state test generator

apps/ex_wire/lib/ex_wire/adapter/tcp/server.ex, apps/ex_wire/lib/ex_wire/handshake.ex, apps/ex_wire/test/ex_wire/handshake_test.exs
ExWire.Handshake has been changing over time as we continuously refactor while working on the networking layer. This commit updates the functions to more consistently take an `ExWire.Handshake` struct as a first argument. It also creates a more even flow whether the node is initiating the handshake or is the recipient of the handshake. This mirroring of the code paths makes it easier to reason about and debug.
Why these changes?
===================
In an effort to make the `DEVp2p` session handling easier to reason about (and hence add more messages), I am trying to simplify the TCP module first.
Eventually, we should have `ExWire.Adapter.TCP` be an "adapter", as the name suggests. Currently, it contains all the logic that coordinates the encrypted handshake (and the DEVp2p session …
=> Standardize ExWire.Handshake functions

apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/refunds.ex, apps/evm/lib/evm/sub_state.ex
The same accounts were destroyed multiple times so we were refunding gas for them each time.
fixes https://github.com/poanetwork/mana/issues/242
=> fix merging refunds for account suicides

apps/blockchain/scripts/generate_state_tests.ex, apps/blockchain/test/blockchain/state_test.exs, apps/evm/lib/evm/sub_state.ex
We didn't check logs in GeneralStateTests. Related PR - https://github.com/poanetwork/mana/pull/240
It looks like logs are being calculated right because only two tests started failing due to invalid log hashes:
- `stSystemOperationsTest/CallRecursiveBombLog.json`
- `stSystemOperationsTest/CallRecursiveBombLog2.json`
Changes:
- validate logs from general state tests
- deduplicate logs during substate merging
Resolves https://github.com/poanetwork/mana/issues/232
=> validate logs

.circleci/config.yml, apps/merkle_patricia_tree/mix.exs, mix.lock
Rox was throwing the following error:
````
Unsupported Erlang version.
Is the erlang_nif-sys version up to date in the Cargo.toml?
````
`erlang_nif-sys` was not up to date. We updated it in Rox and open [a PR](https://github.com/urbint/rox/pull/16)
Until our PR gets merged we’ll depend on our fork.
Other changes:
* Updated the circle configuration
Circle was failing to build the newest version of Rox on the [dialyzer step](https://circleci.com/gh/poanetwork/mana/1095)
By restoring from the cache we can use the version of Rox built by the
`build` step which works as expected.
=> Upgrade Rox

apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/address.ex, apps/evm/lib/evm/exec_env.ex, apps/evm/lib/evm/interface/account_interface.ex, apps/evm/lib/evm/interface/mock/mock_account_interface.ex, apps/evm/lib/evm/operation/system.ex, apps/evm/lib/evm/sub_state.ex
Closes https://github.com/poanetwork/mana/issues/277
What?
=====
After a `SELFDESTRUCT` CPP Ethereum increased the specified refund address by the current balance in the contract that is marked for destruction and then set that contract's balance to zero. This lead to a special case where if the refund address is the same as the contract address it would cause the ether to essentially vanish from existence, as described in Quirk 2 of http://swende.se/blog/Ethereum_quirks_and_vulns.html.
We also add a note that we copied and modified from the CPP implementation that speaks to the reason why this is done. It seems there was a consensus issue in the past and it is now tested via the suicide test we now pass.
----
Clean up Notes:
We remove destroy_account functions. Several modules had …
=> Clear balance when calling SELFDESTRUCT

apps/exth_crypto/mix.exs, bin/setup
We attempted to use `manager: :rebar` for the `libsecp256k1` dependency in ExthCrypto's `mix.exs` file, but it is not compiling it correctly. For now, we will compile it manually by calling `rebar compile`.
=> Compile libsecp256k1 manually with rebar

apps/blockchain/lib/blockchain/transaction/signature.ex, apps/blockchain/lib/math_helper.ex
I am getting issues compiling Mana; it seems that the Erlang `:math` module isn't available on my system (Fedora 2.6, elixir 1.6.6, Erlang 8.3.5.4).
This PR replaces that call with the native elixir `Float.floor` call.
=> Replace :math.floor with Float.floor

.circleci/config.yml, .tool-versions
Dialyzer's PLT is not caching correctly in CI. We make some changes to the config to fix that. Note that we unpack and pack the PLT into a directory because it turns out there is a bug in circle ci when trying to cache the same directory (in this case we would want to cache `_build` twice). So for the PLT we cache a plt directory we create.
We also want to cache the PLT in relation to our elixir/erlang versions. For that reason, we add a `.tool-versions` file that keeps track of the versions we are using.
=> Cache dialyzer's PLT in CI

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/ex_wire/lib/ex_wire/handler.ex, apps/ex_wire/lib/ex_wire/handler/pong.ex, apps/ex_wire/lib/ex_wire/handshake.ex, apps/ex_wire/lib/ex_wire/handshake/eip_8.ex, apps/ex_wire/lib/ex_wire/handshake/struct/auth_msg_v4.ex, apps/ex_wire/lib/ex_wire/kademlia/bucket.ex, apps/ex_wire/lib/ex_wire/message.ex, apps/ex_wire/lib/ex_wire/message/find_neighbours.ex, apps/ex_wire/lib/ex_wire/message/neighbours.ex, apps/ex_wire/lib/ex_wire/protocol.ex, apps/ex_wire/lib/ex_wire/struct/block_queue.ex, apps/ex_wire/lib/ex_wire/struct/peer.ex, apps/exth_crypto/lib/aes.ex, apps/exth_crypto/lib/ecies/parameters.ex, apps/exth_crypto/lib/exth_crypto.ex, apps/exth_crypto/lib/hash.ex, apps/exth_crypto/lib/hash/keccak.ex
Fix several issues with type definitions. Many were mistyped. Others assumed a module was aliased, and others just assumed that a type existed when it didn't. Not all of them were listed in `.dialyzer.ignore-warnings` but they show up when running dialyzer locally.
=> Fix mis-typed types

apps/evm/lib/evm/sub_state.ex, apps/evm/test/evm/sub_state_test.exs, apps/evm/test/evm_test.exs
Following Homestead tests fixed:
- "stRandom/randomStatetest324.json",
- "stRandom2/randomStatetest418.json",
- "stTransitionTest/createNameRegistratorPerTxsNotEnoughGasBefore.json",
- "stWalletTest/walletAddOwnerRemovePendingTransaction.json",
- "stWalletTest/walletChangeOwnerRemovePendingTransaction.json",
- "stWalletTest/walletChangeRequirementRemovePendingTransaction.json",
- "stWalletTest/walletConfirm.json",
- "stWalletTest/walletRemoveOwnerRemovePendingTransaction.json",
=> add new logs to the end of list

apps/blockchain/scripts/sync_with_infura.ex
Exthereum timeout errors weren't being caught by the `rescue` statment.
=> Catch timeout errors in the `sync_with_infura` script

apps/blockchain/scripts/sync_with_infura.ex
Before we'd have to rebuild the blocktree every time we ran
`sync_with_infura` this saves the blocktree to the state database so we
don't have to do that anymore.
=> Save block_tree state in `sync_with_infura` script

apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/configuration.ex, apps/evm/lib/evm/configuration/frontier.ex, apps/evm/lib/evm/configuration/homestead.ex
fixes https://github.com/poanetwork/mana/issues/325
From [EIP2](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md):
```
If contract creation does not have enough gas to pay for the final gas fee for adding the contract code to the state, the contract creation fails (i.e. goes out-of-gas) rather than leaving an empty contract.
```
merge after https://github.com/poanetwork/mana/pull/323
=> EIP2: out of gas error on contract creation if not enough gas

apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/exec_env.ex, apps/evm/lib/evm/message_call.ex, apps/evm/lib/evm/operation/system.ex
We need to store created accounts in the current evm execution and pass them to the nested message calls. 
From EIP 150:
```If SELFDESTRUCT hits a newly created account, it triggers an additional gas cost of 25000 (similar to CALLs).```
=> fix nested create suicide EIP150

apps/evm/lib/block/header.ex, apps/evm/test/block/header_test.exs, apps/evm/test/support/ethereum_common_tests_helper.ex
Closes https://github.com/poanetwork/mana/issues/342
What changed?
============
We add Ethereum common tests that test the difficulty calculation described under the "Block Header Validity" section of the Yellow Paper.
In the common tests, under the `BasicTests` directory, there are several files that test difficulty. Some are generated manually while others are refilled automatically. We make use of the file `difficultyFrontier.json`. It is worth noting that those tests do not contain difficulty tests only for the Frontier chain. They also test other forks (like Homestead). I am not sure why they have `Frontier` in the name since other forks are included.
In order to limit which tests run, so that we can pass tests progressively as we implement various forks, we check the block number in …
=> Add Ethereum common difficulty tests

apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/configuration.ex, apps/evm/lib/evm/configuration/eip150.ex, apps/evm/lib/evm/configuration/eip158.ex, apps/evm/lib/evm/configuration/frontier.ex, apps/evm/lib/evm/configuration/homestead.ex
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md
=> limit code size EIP170

apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/transaction/signature.ex, apps/blockchain/lib/blockchain/transaction/validity.ex, apps/blockchain/test/blockchain/transaction/validity_test.exs, apps/evm/lib/evm/configuration.ex, apps/evm/lib/evm/configuration/eip150.ex, apps/evm/lib/evm/configuration/eip158.ex, apps/evm/lib/evm/configuration/frontier.ex, apps/evm/lib/evm/configuration/homestead.ex
Closes https://github.com/poanetwork/mana/issues/352
What changed?
=============
We validate that a transaction signature's s-value is not too high. How high the s-value can be depends on the fork (Homestead changed the value). We make use of `EVM.Configuration` to ensure that all forks provide the correct s-value.
=> Validate signature's s-value in transaction validity

apps/ex_wire/lib/ex_wire/framing/frame.ex, apps/ex_wire/lib/ex_wire/handshake/struct/auth_msg_v4.ex, apps/ex_wire/lib/ex_wire/packet.ex, apps/ex_wire/lib/ex_wire/packet/transactions.ex, apps/exth_crypto/lib/exth_crypto/mac.ex
Part of a continued effort in completing https://github.com/poanetwork/mana/issues/27
What changed?
============
Fix several dialyzer issues. Some simply break contract because they allow a `nil`, while others were slightly more complicated (like the supertype being a `struct()` instead of a `%{}`).
=> Fix some dyalizer issues

apps/blockchain/test/blockchain/state_test.exs
The `test_group` variable, which is used to determine known failures, was incorrectly returning the wrong part of the path (likely due to us changing from a relative path to an absolute path at some point). It was usually returning `mana`. We reverse the index to grab the elements from the end of the list so that we always get the group name, regardless of where the path starts.
=> Fix test_group from path retrieval in state tests

README.md, apps/blockchain/lib/blockchain/contract.ex, apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/lib/eth_common_test/helpers.ex, apps/blockchain/test/blockchain/contract_test.exs, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/configuration.ex, apps/evm/lib/evm/configuration/byzantium.ex, apps/evm/lib/evm/configuration/eip150.ex, apps/evm/lib/evm/configuration/eip158.ex, apps/evm/lib/evm/configuration/frontier.ex, apps/evm/lib/evm/configuration/homestead.ex
This closes #368.
What changed?
=============
We increment the nonce of an account when it is touched on CREATE (operation or
transaction call). We change the implementation of `start_nonce` introduced in
https://github.com/poanetwork/mana/pull/353, to `increment_nonce_on_create`
since I think that may be what is described in EIP 161 part a:
> a. Account creation transactions and the CREATE operation SHALL, prior to
the execution of the initialisation code, increment the nonce over and
above its normal starting value by one (for normal networks, this will be
simply 1, however test-nets with non-zero default starting nonces will be
different).
Note that the test-nests comment above would be configured at the chain level
not at the EVM-fork level. So I think it is safe to replace the …
=> Increment nonce of touched accounts on CREATE

bin/setup
`bin/setup` now works on Linux. Tested with Fedora 26 and Debian 9.
=> Enable setup for various Linux platforms

apps/blockchain/test/blockchain_test.exs
This is a first step for https://github.com/poanetwork/mana/issues/330
What changed?
=============
We are currently running all blockchain tests (that is the ethereum common tests under `/BlockchainTests` directory) in a single ExUnit `test`. So we can't get any of the automatic parallelization that ExUnit's `async: true` provides.
Here we split each hardfork we are testing into a separate process. We then combine the results and assert whether or not the ExUnit test succeeded or failed as a whole.
In a very limited sample (two CI builds), this seems to shave between 6 and 7 minutes off the build: the [latest build](https://circleci.com/workflow-run/0bc29d11-7d5e-494d-a819-7281d37ea600) I had seen was 32:13 minutes, and the two runs for this PR were at …
=> Run Blockchain Tests in different processes

apps/blockchain/scripts/evm_runner.ex, apps/evm/README.md, apps/evm/lib/evm/operation/environmental_information.ex, apps/evm/test/evm/operation/environmental_information_test.exs
What Changed
============
When `size` was 0 on callcode we were returning 0. Instead we should be
returning the machine state unchanged. This didn't cause an error until
block #116524 where callcode was called with `size = 0`.
Other changes
-----------
* Added a script to run raw EVM code. I used this while debugging this
issue.
* Minor EVM README fix
=> Fix bug at block #116524

apps/blockchain/mix.exs, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/blockchain/test/support/async_common_tests.ex
This relates to #330
What changed?
=============
We are currently running all state tests (that is the ethereum common tests under `/GeneralStateTests` directory) in a single ExUnit test. So we can't get any of the automatic parallelization that ExUnit's `async: true` provides.
Here we split each hardfork we are testing into a separate process. We then combine the results and assert whether or not the ExUnit test succeeded or failed as a whole.
We have already done this in `blockchain_tests` so we extract common functionality related to spawning processes for each fork into a shared module called `AsyncCommonTests` (could use a better name).
From a very brief look the builds, it looks like this shaves another 4-6 minutes off of the build.
So https://github.com/poanetwork/mana/pull/374 and …
=> Run state tests in different processes

.circleci/config.yml, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, bin/test_command_for_node
This closes #330. It is the third step (after #374 and #376) to improve the build times.
What changed?
=============
We parallelize the builds by separating the blockchain common tests and state tests into their own builds and then the rest of the tests into another build.
We could use some other CircleCI features such as `--split-by=timings`, but since we only have two tests that take a really long time, and we know which tests those are, it seems simpler to separate those two tests into their own containers.
From a very limited set of data, it seems like this saves us ~9 minutes on a single build run.
=> Parallelize tests by separating blockchain/state_tests

apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs
Part of https://github.com/poanetwork/mana/issues/330
What changed?
=============
In order to improve the build time, we split our tests by forks in previous commits. When we started using `Task.async_stream`, it became apparent that we could just split tests by groups of tests rather than by forks. What we end up doing here is splitting all tests into ten groups for each fork. We then run those tests asynchronously.
We tested splitting tests into 20 groups but we did not see an improvement in build times. I think that is due to the fact that the build can only be as fast as the slowest test we have. And I think one (or more) of the tests we have take several minutes.
For a sample of CI runs in this branch, see https://circleci.com/gh/poanetwork/workflows/mana/tree/gv-split-tests-by-direct …
=> Split tests by groups instead of forks

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/block.ex, apps/evm/lib/block/header.ex, apps/evm/test/block/header_test.exs
Why:
We would like to implement the next difficulty calculation for hardfork
Byzantium. With the current setup we would need to pass more information
about the chain into EVM.Block.get_difficulty. Rather than couple EVM
and Blockchain more, it would be nice to clean up the separation.
This commit:
Extracts difficulty hardfork check to Blockchain.Block instead of
passing chain parameters to Block.Header. The logic for the `chain`
lives in the Blockchain, so it makes sense make our Homestead vs
Frontier check there.
=> Extract difficulty hardfork check to Block

apps/blockchain/scripts/generate_blockchain_tests.ex
What changed?
=============
Much like we did for `blockchain_tests`, `state_tests` and the `generate_state_tests` script, we parallelize the `generate_blockchain_tests` script.
=> Parallelize generate_blockchain_tests script

bin/setup
Otherwise, ./bin/setup will fail on new Ubuntu installs
=> add erlang-dev to list of installed ubuntu packages

apps/ex_wire/.iex.exs, apps/ex_wire/config/dev.exs, apps/ex_wire/lib/ex_wire.ex, apps/ex_wire/lib/ex_wire/p2p.ex, apps/ex_wire/lib/ex_wire/p2p/server.ex, apps/ex_wire/lib/ex_wire/packet/status.ex, apps/ex_wire/lib/ex_wire/peer_supervisor.ex, apps/ex_wire/lib/ex_wire/sync.ex
This is part of https://github.com/poanetwork/mana/issues/166 and https://github.com/poanetwork/mana/issues/167.
Summary
========
The networking layer was not handling Disconnect, Ping, and Status packages. The first two are DEVp2p and the Status packet is the first packet that must be sent for the Ethereum Wire Protocol (after the encrypted and DEVp2p handshakes).
Details
========
Adding Subscribers to Connection struct
-----------------------------------------
First we add `subscribers` to `ExWire.P2P.Connection` struct. For a while I was resisting doing this since I wanted `P2P` to be a pure module without having to know about the socket connection. Ideally it could just respond something like `{:send, packet}` and the `P2P.Server` would handle the actual communication to the socket. …
=> Handle Disconnect, Ping, and Status packets

apps/blockchain/lib/blockchain/block.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/lib/blockchain/transaction/validity.ex, apps/blockchain/test/blockchain/block_test.exs, apps/blockchain/test/blockchain/transaction/validity_test.exs
Why:
We should be using `Transaction.execute_with_validation` in our blockchain block instead of skipping validations with `Transaction.execute`. We were skipping these previously because it was causing some blockchain common tests to fail but I think we want to check our transactions are valid to get all the tests passing eventually.
This PR:
Uses `Transaction.execute_with_validation` in `apps/blockchain/lib/blockchain/block.ex` and makes the required changes to our existing tests. Due to https://github.com/ethereum/tests/issues/503 we needed to introduce a `check_account_validity` to handle cases where the sender account doesn't exist. This removes the invalid case of `missing_account` as if the account is missing but there is a cost for the transaction, the transaction will still be …
=> Validate before executing transactions

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/evm/lib/evm/configuration.ex, apps/evm/lib/evm/configuration/byzantium.ex, apps/evm/lib/evm/configuration/constantinople.ex, apps/evm/lib/evm/configuration/eip150.ex, apps/evm/lib/evm/configuration/eip158.ex, apps/evm/lib/evm/configuration/frontier.ex, apps/evm/lib/evm/configuration/homestead.ex, apps/evm/lib/evm/functions.ex, apps/evm/lib/evm/gas.ex, apps/evm/lib/evm/interface/account_interface.ex, apps/evm/lib/evm/interface/mock/mock_account_interface.ex, apps/evm/lib/evm/operation/environmental_information.ex, apps/evm/lib/evm/operation/metadata/environmental_information.ex
resolves https://github.com/poanetwork/mana/issues/418
`extcodehash` was tested against  https://github.com/ethereum/tests/pull/484
=> implement extcodehash

.circleci/config.yml, README.md, apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/account/address.ex, apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/blockchain/test/blockchain/account/address_test.exs, apps/blockchain/test/blockchain/block_test.exs, apps/blockchain/test/blockchain/contract/create_contract_test.exs, apps/blockchain/test/blockchain/transaction_test.exs, apps/evm/lib/evm/address.ex, apps/evm/lib/evm/operation/system.ex, apps/ex_wire/config/dev.exs
Block number 177610 in the mainnet has an account that is pushed into
the stack as an integer. The account when represented as an integer does
not have a leading zero, but when represented as hex, it has `00` as its
first two characters.
This led to a subtle bug, where the balance of the account in question
seemed to be zero, when in reality we were checking the wrong account's
balance.
To fix this issue, we ensure that the addresses coming from the EVM (via
the account interface) are all turned into
`Blockchain.Account.Addresses` which must have `160` bits. If they are
short, as was the case in the bug, we pad them.
Additionally:
------------
The SubState's touched accounts should have the binary format for the
address of an account. The `create` system operation was passing the
result …
=> Turns EVM.address => Account.Address in interface

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/block.ex, apps/blockchain/lib/blockchain/block/holistic_validity.ex, apps/blockchain/lib/blockchain/contract.ex, apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/lib/blockchain/contract/message_call.ex, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/scripts/generate_state_tests.ex, apps/blockchain/test/blockchain/block_test.exs, apps/blockchain/test/blockchain/contract/message_call_test.exs, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain/transaction_test.exs
Resolves https://github.com/poanetwork/mana/issues/394
Summary
========
Adds a transaction status of `0` for failure and `1` for success. This transaction status is included in the transaction receipts if the block number is past the Byzantium hardfork.
More detail
===========
* We update `Transaction.execute`, as well as `MessageCall.execute` and `ContractCreate.execute` to return the status specified as Gamma^z in section 6, Transaction Execution, of the Yellow Paper (0 for failure, 1 for success).
* After the Bynzatium fork, the transaction receipt's state root should include a `0` if the transaction failed or a `1` if it succeeded. This is EIP 658.
=> Implement EIP-658

README.md, apps/evm/README.md, apps/evm/lib/evm/logger.ex
While debugging why the blockchain would not sync past block `177610`, we discovered some helpful debugging tools. This commit documents those in the main README, and we also update the EVM README to use the `EVM.Logger`.
=> Add debugging tools documentation

apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/lib/blockchain/contract/message_call.ex, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/test/blockchain/contract/create_contract_test.exs, apps/blockchain/test/blockchain/contract/message_call_test.exs
Part of https://github.com/poanetwork/mana/issues/416
To work with cache instead of permanent storage in evm we need to add accounts state (balance changes etc) caching to `AccountInterface`. 
Currently, we are returning state with applied changes from `CreateContract` and `MessageCall` modules.
Changes:
- return account_interface from `CreateContract` and `MessageCall` to apply changes in `Transaction` module
=> return account_interface instead of state

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/chain.ex, apps/blockchain/lib/blockchain/mix/tasks/common_tests.run.ex, apps/blockchain/test/blockchain_test.exs, apps/blockchain/test/support/blockchain_test_runner.ex
What changed?
============
Creates `mix common_tests.run` mix task to run a single blockchain test file, with an optional hardfork.
This task uses much of the same logic as does the `blockchain_test.exs` test. So we extract a `BlockchainTestRunner` module to house all that common logic related to running a single blockchain test file.
Why?
===
When we debug failing blockchain tests, it is often hard to run a single test. It is possible to do so by modifying certain pieces of the `test/blockchain_test.exs` file, but that requires some knowledge of the structure of the test setup, and it is both cumbersome and time consuming. With this new mix task, we can simply specify the file we need to run and it will run that test.
A note on mix task
==================
The advantage of creating this …
=> Create common_tests.run mix task

apps/blockchain/test/blockchain_test.exs
What changed?
=============
This is something that was missed in https://github.com/poanetwork/mana/pull/444
The `BlockchainTestRunner` now returns test results with `{:pass, result}` or `{:fail, result}`, where `result` is equivalent to what used to be returned from the same logic before `BlockchainTestRunner` was extracted. The filtering logic for test failures was updated correctly to expect the `{:fail, _}` tuple, but the error message constructor was not updated to expect it. We update that here.
=> Update blockchain_test pattern matching

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/chain.ex, apps/blockchain/lib/mix/tasks/common_tests.run.ex, apps/blockchain/lib/mix/tasks/state_tests.run.ex, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/support/state_test_runner.ex
What changed?
============
Adds `mix state_tests.run` task to enable us to run a single state test
file quickly. The mix task also takes an optional `--fork` flag to only
run tests in that hardfork.
This task is the counterpart to the blockchain task `mix
common_tests.run` for state tests.
Since this mix task uses much of the same logic as the
`test/blockchain/state_test.exs` we extract that into `StateTestRunner`
module.
=> Add mix state_tests.run task

apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/lib/blockchain/contract/message_call.ex, apps/blockchain/lib/blockchain/interface/account_interface.ex, apps/blockchain/lib/blockchain/interface/account_interface/cache.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/test/blockchain/contract/create_contract_test.exs, apps/blockchain/test/blockchain/contract/message_call_test.exs, apps/blockchain/test/blockchain/interface/account_interface/cache_test.exs, apps/blockchain/test/blockchain/interface/account_interface_test.exs
with https://github.com/poanetwork/mana/pull/440 resolves https://github.com/poanetwork/mana/issues/416
Changes: 
- Do not modify Merkle Patricia Tree during EVM execution (it's read-only)
- Commit storage changes only on successful EVM execution
- Use temporary storage in EVM
=> cache storage operations

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/chain.ex, apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/lib/blockchain/transaction/validity.ex, apps/blockchain/scripts/generate_blockchain_tests.ex, apps/blockchain/scripts/generate_state_tests.ex, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/support/state_test_runner.ex, apps/evm/lib/evm/configuration.ex, apps/evm/lib/evm/configuration/byzantium.ex, apps/evm/lib/evm/configuration/constantinople.ex, apps/evm/lib/evm/configuration/eip150.ex, apps/evm/lib/evm/configuration/eip158.ex, apps/evm/lib/evm/configuration/frontier.ex, apps/evm/lib/evm/configuration/homestead.ex, apps/evm/lib/evm/functions.ex, apps/evm/lib/evm/gas.ex, apps/evm/lib/evm/message_call.ex, apps/evm/lib/evm/operation/system.ex, apps/evm/lib/evm/refunds/sstore.ex, apps/ex_wire/lib/ex_wire/config.ex
What?
=====
We turn `EVM.Configuration` into a Behaviour instead of a protocol.
Why?
=====
Behaviours and Protocols are two ways to implement polymorphism in
Elixir. When we want a module to behave the same way as other modules,
we want it to satisfy a behaviour (e.g. `GenServer`). When we want to
create a somewhat generic set of operations on different types, we use
protocols (e.g. `Enumerable` working on lists, ranges, etc).
Since the `EVM.Configuration` lands on the first camp, we should use a
`Behaviour` for it. This has the side-effect of cleaning up some
dialyzer errors that made no sense previously, such as an `Atom` not
having the `EVM.Configuration` protocol implemented.
=> Turn EVM.Configuration into a behaviour

apps/blockchain/lib/blockchain/chain.ex, chains/eip161_test.json
It turns out we have been using `EIP150`'s chain configuration for `EIP158` (during tests). A more accurate chain to use would be `EIP161` since `EIP161` is what superseded `EIP158`. We should also consider renaming EIP150 -> TangerineWhistle and EIP58 (EIP161) -> SpuriousDragon, but we leave that for future work.
This change does not have an effect in number of tests passed since most of the values that differ between EIP150 and EIP158 are being sourced via the `EVM.Configuration.EIP158` and not via the chain struct.
=> Use EIP161 chain config for EIP158

apps/blockchain/lib/bit_helper.ex, apps/blockchain/lib/blockchain.ex, apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/account/address.ex, apps/blockchain/lib/blockchain/account/storage.ex, apps/blockchain/lib/blockchain/block/holistic_validity.ex
- Minor documentation updates to fix formatting, clarify text and check Yellow Paper references.
- It may be useful to add a small amount of documentation to Blockchain.Account.Storage functions.
- I would like to create a better shorthand for referring to the Yellow Paper. Is there room for a glossary or table with common reference points? If so, where would be the best place for this in the current documentation context?
=> Ag yp equation updates

.dialyzer.ignore-warnings, README.md, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/lib/blockchain/transaction/account_cleaner.ex, apps/blockchain/scripts/generate_state_tests.ex, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/support/state_test_runner.ex
Closes https://github.com/poanetwork/mana/issues/460
What changed?
============
Introduces a step in our state tests to create the miner/beneficiary/coinbase account immediately before setting up accounts in the `pre` state. It also adds a step after the transaction execution to cleanup the miner account if we are past EIP-161 (since that is when we start cleaning up empty accounts).
Why is this needed?
===================
It turns out the state tests are not supposed to be run completely in a vacuum. Other implementations' test runners duplicate some of their blockchain implementation's functionality in order to make the state tests run more like blockchain tests.
We have state tests that are failing because of state root hash mismatches: these tests should be simulating giving a miner …
=> Simulate coinbase reward/clean-up in state tests

apps/blockchain/lib/blockchain/blocktree.ex, apps/blockchain/test/blockchain/blocktree_test.exs, apps/blockchain/test/support/state_test_runner.ex, apps/ex_wire/lib/ex_wire/struct/block_queue.ex, mix.exs
fixes https://github.com/poanetwork/mana/issues/456
fixes https://github.com/poanetwork/mana/issues/446
We don't have to keep in memory all blocks from the beginning. I think this data structure was needed when the best block was assigned by traversing full blocktree. But the algorithm of finding the best block was changed in https://github.com/poanetwork/mana/pull/303. Now, to find the best block we need only the current block and previous best block.
=> do not keep all blocks in memory

.dialyzer.ignore-warnings, apps/blockchain/lib/eth_common_test/blockchain_test_runner.ex, apps/blockchain/lib/eth_common_test/state_test_runner.ex, apps/blockchain/lib/mix/tasks/common_tests.run.ex, apps/blockchain/lib/mix/tasks/state_tests.run.ex, apps/blockchain/scripts/generate_state_tests.ex, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs
Since the `StateTestRunner` and `BlockchainTestRunner` modules are no longer used simply from within the `state_test.exs` and `blockchain_test.exs`, but are also used my mix tasks, we move them out of the `test/support` directory into the `lib/eth_common_test` directory.
Not doing so throws warnings during compilation that state that `StateTestRunner` and `BlockchainTestRunner` are not defined. It also forces us to run the mix tasks by prepending them with `MIX_ENV=test`.
=> Move test runners out of test/support

apps/blockchain/lib/blockchain/block.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/lib/blockchain/transaction/signature.ex, apps/blockchain/lib/blockchain/transaction/validity.ex, apps/blockchain/lib/eth_common_test/state_test_runner.ex, apps/blockchain/scripts/sync_with_infura.ex, apps/blockchain/test/blockchain/transaction/validity_test.exs, apps/blockchain/test/blockchain/transaction_test.exs
Why:
We should be validating signatures using v = 27 | 28 | CHAIN_ID * 2 + 35
| CHAIN_ID * 2 + 36 but we are currently only using v = 27 | 28.
This PR:
Adds the additional valid values for v. This means we need to pass
around the chain instead of only evm_config for validating sender
signatures.
=> EIP-155 signature schema

apps/blockchain/lib/eth_common_test/helpers.ex, apps/blockchain/lib/eth_common_test/state_test_runner.ex, apps/blockchain/scripts/generate_state_tests.ex, apps/blockchain/test/blockchain/state_test.exs
In in the previous pull requests (https://github.com/poanetwork/mana/pull/462, https://github.com/poanetwork/mana/commit/bfe50d73432450da18a98de12c6bbcd8265cea85), `EIP158` was renamed to `SpuriousDragon` and `EIP150` was renamed to `TangerineWhistle`
- We didn't run `EIP158` and `EIP150` hard fork tests
- State tests generation script did not run `EIP158` and `EIP150` hard fork tests
=> fix fork configuration resolving

.dialyzer.ignore-warnings, apps/evm/lib/evm/gas.ex, apps/evm/lib/evm/machine_state.ex, apps/evm/test/evm/gas_test.exs
Description
===========
The function `Gas.cost` was a bit confusing, especially since we had to constantly check whether or not the `with_status` flag had been passed in order to know what values to return. This also tripped up Dialyzer in https://github.com/poanetwork/mana/pull/473#discussion_r222670772, and I wanted to make sure this wasn't a real bug Dialyzer had discovered.
Here we separate `cost` and `cost_with_status` into two functions and clarify the typespecs to more clearly document what the functions return (e.g. :original | :changed instead of atom(), Gas.t instead of number()).
=> Clarify Gas.cost/cost_with_status

apps/evm/lib/evm/message_call.ex, apps/evm/test/evm/message_call_test.exs
What changed
============
Before we were always calling MachineState.maybe_set_active_words when
message calls were made. We shouldn't have been setting active words
when out_size == 0.
Referencing from the Yellow Paper(296):
"Referencing a zero length range (e.g. by attempting to pass it as the input range to a CALL) does not require memory
to be extended to the beginning of the range."
=> Fix consensus bug at block 1237678

apps/blockchain/lib/blockchain/transaction.ex
Why:
We're pulling the config based on the block number instead of using
chain.evm_config.
This PR:
Updates the transaction to use an evm_config generated from the chain
and the current block number.
=> Use config variable instead of chain

apps/evm/lib/evm/memory.ex, apps/evm/test/evm/memory_test.exs
[Transaction 0x9d1b51c65d0624985e41447a7966bf7287a08dc9334b85dac9e0a1ab5dd7a9c1](https://etherscan.io/tx/0x9d1b51c65d0624985e41447a7966bf7287a08dc9334b85dac9e0a1ab5dd7a9c1) calls a `CODECOPY` with offset > 0xffffffffe0
causing the memory to overflow. Since the data size zero the write can
be skipped all together.
=> Fix memory error at 1417555

README.md
Why:
We haven't updated these numbers in a while.
This PR:
Updates the block numbers that we've synced up to.
=> Update readme block numbers

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/account/repo.ex, apps/blockchain/lib/blockchain/account/repo/cache.ex, apps/evm/lib/evm/account_repo.ex, apps/evm/lib/evm/mock/mock_account_repo.ex
This fixes the majority of the ignored dialyzer warnings for `blockchain/account/repo.ex`, `blockchain/account/repo/cache.ex`, `evm/mock/mock_account_repo.ex`, `evm/account_repo.ex`. They were ignored as part of https://github.com/poanetwork/mana/pull/494. 
Description
===========
We start by removing the ignored warnings for `blockchain/account/repo` and `evm/mock/mock_account_repo`. This triggered a cascade of fixes that spanned more modules that just those two. In fact, some warnings led us to understand that some of the functions were not used at all:
Removals
--------
- Remove add_wei from EVM.AccountRepo. It is not called from the evm app and thus does not need to be part of the behaviour. It remains as part of the `Blockchain.Account.Repo`.
- Remove AccountRepo.new_contract_address …
=> Fix dialyzer warnings for AccountRepo implementations

.dialyzer.ignore-warnings, apps/blockchain/lib/blockchain/account/repo/cache.ex, apps/blockchain/lib/blockchain/block.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/test/blockchain/account/repo_test.exs
This fixes the last dialyzer warnings introduced in https://github.com/poanetwork/mana/pull/494
Description
===========
Several typespec definitions claimed they accepted or returned a `EVM.state()` type. But that is not accurate. The all take a `MerklePatriciaTree.Trie.t()`.
Dialyzer was throwing warnings in `blockchain/account/repo.ex` because it thought the `commit` function was passing `EVM.state()` into the `new` function, and that it would fail in that function call.
Here is the full error. Note that `EVM.state()` is defined as a `%{account_address => account}` mapping, which is why we see that being passed as the first argument into `Account.Repo.new`
```elixir
apps/blockchain/lib/blockchain/account/repo.ex:50: The call
'Elixir.Blockchain.Account.Repo':new(#{<<_:160>> => #{ …
```
=> Correct EVM.state() to Trie.t()

README.md, apps/blockchain/test/blockchain/state_test.exs, apps/evm/lib/evm/memory.ex, apps/evm/lib/evm/message_call.ex, apps/evm/lib/evm/operation/stack_memory_storage_and_flow.ex, apps/evm/test/evm/memory_test.exs, apps/evm/test/evm/message_call_test.exs
fixes https://github.com/poanetwork/mana/issues/491
Changes:
- We weren't considering `out_size` parameter when we were writing to the memory after message call. If it is smaller than output's size than we should truncate output
- Truncating logic in `Memory` module was wrong
=> fix writing to memory

apps/evm/lib/evm/mock/mock_account_repo.ex, apps/evm/lib/evm/operation/environmental_information.ex, apps/evm/test/evm/operation/environmental_information_test.exs
fixes https://github.com/poanetwork/mana/issues/500
We're pushing zero to stack if invalid params for `extcodecopy` are provided. We should return unmodified machine state
=> fix extcodecopy

apps/blockchain/lib/mix/tasks/state_tests.run.ex
OptionParser aliases are not for aliasing two different `--options` but rather for creating a shorthand version of an existing alias.
So this _does not_ create a `hardfork` alias for `fork`:
```elixir
[hardfork: :fork]
```
But this creates an alias for `--fork` that can be used with `-f`
```elixir
[f: :fork]
```
=> Fix state_tests.run --fork alias

apps/evm/lib/evm/sub_state.ex, apps/evm/test/evm/refunds_test.exs, apps/evm/test/evm/sub_state_test.exs, apps/evm/test/evm/vm_test.exs
While working on https://github.com/poanetwork/mana/issues/506 it was discovered that substate deduplication works wrong
We used `Enum.dedup` for `selfdestruct_list` and `touched_accounts`
deduplication. It's wrong because it deduplicates only consecutive
values. MapSet has required functionality for deduplication
=> fix substate deduplication

apps/blockchain/lib/blockchain/account/inspector.ex, apps/blockchain/test/blockchain/account/inspector_test.exs
Description
===========
Adds a `Blockchain.Account.Inspector` module to more easily inspect the contents of an account. This is mostly for debugging purposes, and it is not expected that it would be used in production. It takes an account address (hex) and prints out the balance, nonce, storage root, and code hash.
=> Add Blockchain.Account.Inspector

README.md, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/builtin/rip160.ex, apps/evm/lib/evm/message_call.ex, apps/evm/test/evm/message_call_test.exs
Relates to https://github.com/poanetwork/mana/issues/370
This fixes GeneralStateTests/stSpecialTest/failed_tx_xcf416c53 in state tests for SpuriousDragon and Byzantium, and it fixes it in blockchain tests for SpuriousDragon. Strangely, it does not solve it for Byzantium. I will continue working on a Byzantium fix, but I think this can be committed now as a unit of work.
Description
===========
During the empty account cleanup that ensued after the Spurious Dragon hardfork, a consensus issue arose. Geth was not reverting removed empty accounts (un-deleting them as it where) when a call was OOG. Parity was reverting the removal.
During cleanup, it was discovered that there was one more idiosyncrasy: both Geth and Parity had failed to revert the clean up of an empty account when an inner …
=> Touch RIPEMD account on failure

apps/blockchain/lib/blockchain/block/holistic_validity.ex, apps/evm/lib/evm/operation/system.ex, apps/evm/test/evm/operation/system_test.exs
fixes https://github.com/poanetwork/mana/issues/498
We were prepending logs from contract creation to accumulated logs.
This is wrong. Logs order have to be from old to new
=> fix logs order in receipts

apps/blockchain/lib/mix/tasks/blockchain_tests.run.ex, apps/blockchain/lib/mix/tasks/state_tests.run.ex
Description
===========
The mix task for running a single blockchain test was created first, and since the task lives in the blockchain app, it was named `common_tests.run`. But now that we also have a `state_tests.run` mix task, the `common_tests.run` task name is confusing. We update it to be `blockchain_tests.run`.
=> Rename common_tests.run task to blockchain_tests.run

apps/blockchain/test/blockchain/state_test.exs, apps/evm/lib/evm/message_call.ex, apps/evm/test/evm/message_call_test.exs
We should set `last_return_data` to empty binary on message call failure because there is no return data.
=> set last_return_data to empty binary on message call failure

README.md, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/builtin/mod_exp.ex
We should return empty binary if mod_size is equal to zero
fixes https://github.com/poanetwork/mana/issues/524
=> fix modexp output

apps/evm/README.md, apps/evm/lib/evm/logger.ex, apps/evm/lib/evm/machine_state.ex, apps/evm/lib/evm/vm.ex
As I work on debugging why we're failing to sync the mainnet, I have found these changes to be helpful. I am unsure whether or not this is something we want to use, since I know the EVM.Logger's original intent was to compare the output with parity. But I have found that most of my debugging is done against Geth's stacktraces in [Etherescan](https://etherscan.io). A sample stack trace can be found [here](https://etherscan.io/vmtrace?txhash=0xec32243bad69039271ae01362ec4916be9fbf546e5356db420b1267ac1a038a3#raw).
Description
===========
A lot of our debugging is happening as we compare stack traces against geth's vm traces found in Etherescan.
To that end, we make the following changes so that debugging is easier:
1. Add a `step` key to `MachineState` so that we know how many cycles the vm …
=> Improve EVM.Logger output

apps/evm/lib/evm/memory.ex, apps/evm/lib/evm/operation/environmental_information.ex
`extcodehash` was failing because we were trying to calculate sha3 hash
from integer instead of binary
```
12:26:51.523 [error] Task #PID<0.909.0> started from #PID<0.74.0> terminating
** (ArgumentError) argument error
:keccakf1600.sha3_256(1)
```
We should convert integer address from stack to binary
=> fix extcodehash opcode parameter

apps/blockchain/scripts/generate_state_tests.ex, apps/evm/lib/evm/configuration.ex, apps/evm/lib/evm/configuration/constantinople.ex
eip1283 (sstore gas cost changes) was disabled because common tests
weren't ready
Passing Constantinople state tests 5309/5311= 100.0%
Passing Constantinople blockchain tests 5347/5349 = 100.0%
=> turn on eip1283

apps/evm/lib/evm/operation/environmental_information.ex, apps/evm/test/evm/operation/environmental_information_test.exs
Resolves https://github.com/poanetwork/mana/issues/528
Description
============
We were failing to sync past block 2325632 on the mainnet because transaction `0xec32243bad69039271ae01362ec4916be9fbf546e5356db420b1267ac1a038a3` has an `extcodecopy` operation with positive `size` but the code is empty.
In order to fix that, we remove the conditionals on `extcodecopy` that returned an unchanged `machine_state`. That conditional tested three possibilities with logical ORs, meaning any of these three would return an unchanged `machine_state`:
1. size == 0 -> this is already handled by the Memory.write operation, so we remove the condition.
2. size + mem_offset > EVM.max_int() -> reading the yellow paper, it seems that this condition was wrong. Under `excodecopy` in the appendices outlining …
=> Simplify extcodecopy conditional logic

apps/blockchain/lib/blockchain/contract/create_contract.ex, apps/blockchain/lib/blockchain/transaction.ex, apps/blockchain/lib/blockchain/transaction/account_cleaner.ex, apps/blockchain/lib/blockchain/transaction/validity.ex, apps/evm/lib/evm/configuration.ex, apps/evm/lib/evm/configuration/byzantium.ex, apps/evm/lib/evm/configuration/constantinople.ex, apps/evm/lib/evm/configuration/frontier.ex, apps/evm/lib/evm/configuration/homestead.ex, apps/evm/lib/evm/configuration/spurious_dragon.ex, apps/evm/lib/evm/configuration/tangerine_whistle.ex, apps/evm/lib/evm/functions.ex, apps/evm/lib/evm/gas.ex, apps/evm/lib/evm/message_call.ex, apps/evm/lib/evm/operation/system.ex, apps/evm/lib/evm/refunds/sstore.ex
This is a suggested PR. If it doesn't seem like a good idea, I'd be happy to close this.
The problem
============
The EVM.Configuration files are full of repetitive implementations of functions that simply call the underlying key in a struct,
```elixir
def contract_creation_cost(config), do: config.contract_creation_cost
```
or functions that use a fallback config to call another module's
implementation,
```elixir
def extcodesize_cost(config), do: Frontier.extcodesize_cost(config.fallback_config)
```
This is a lot of duplication both in the functions we write but also in the calling code. We are doing the following a lot,
```elixir
Evm.Configuration.for(config).contrac_creation_cost(config)
```
when we could simply be doing,
```elixir
config.contract_creation_cost
```
In addition, it is …
=> Make EVM.Configuration simpler

apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/account/repo.ex, apps/blockchain/lib/blockchain/account/storage.ex, apps/blockchain/lib/blockchain/block.ex, apps/evm/lib/evm/account_repo.ex, apps/ex_wire/lib/ex_wire/struct/block_queue.ex, apps/merkle_patricia_tree/README.md, apps/merkle_patricia_tree/lib/merkle_patricia_tree/caching_trie.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/storage.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/storage_behaviour.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie/builder.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie/destroyer.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie/fetcher.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie/helper.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie/inspector.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie/storage.ex, apps/merkle_patricia_tree/test/merkle_patricia_tree/caching_trie_test.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree/trie_test.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree_test.exs
We need at least two levels of cache. Right now we have one level that was implemented in https://github.com/poanetwork/mana/pull/433, https://github.com/poanetwork/mana/pull/441, https://github.com/poanetwork/mana/pull/458. 
Now we're committing changes after every transaction. This is ok if there are no invalid blocks. But in real network we will be receiving invalid blocks and we shouldn't write their transaction data to db. 
The idea is to have `CachingTrie`: all storage modification will be made to in-memory trie and saved to disk after successful block validation. Nodes that are not present in in-memory trie will be read from disk.
This will help to validate state root without saving storage modifications to disk.
This PR implements `CachingTrie`. I will replace regular `Trie` with …
=> Mekle Patricia Trie Cache

apps/blockchain/lib/blockchain/ethash.ex, apps/blockchain/test/blockchain/ethash_test.exs
This is part of #541
Description
===========
This implements the `seed_hash/1` function for the `Ethash` algorithm. This particular function can be found in Appendix J, section J.3.1 in the Byzantium Edition of the Yellow Paper.
It's worth noting that previous editions of the yellow paper had the original seed hash as the `keccak(<<0::256>>)` but Geth and Parity has simply used `<<0::256>>` (not the keccak) so that became the canon and is reflected in the Byzantium version of the yellow paper.
See the related issue: https://github.com/ethereum/yellowpaper/issues/312
=> Implement Ethash.seed_hash

apps/blockchain/lib/blockchain/ethash.ex, apps/blockchain/test/blockchain/ethash_test.exs, apps/exth_crypto/lib/exth_crypto/hash/keccak.ex
This is part of #541
Description
===========
Adds the initial cache calculation to `Ethash` algorithm. This is found in Appendix J, section J.3.2, of the Yellow Paper.
The initial cache is an array of of size (cache_size/j_hashytes) where each element is calculated based on the previous element. Each element is encrypted with keccak 512, so we expose that function from ExthCrypto.
YP section
-----------
=> Add Ethash.initial_cache

apps/cli/lib/sync.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/caching_trie.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/db.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/db/ets.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/db/rocksdb.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie_storage.ex, apps/merkle_patricia_tree/test/merkle_patricia_tree/caching_trie_test.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree/db/ets_test.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree/db/rocksdb_test.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree/trie_test.exs, bin/setup
Optimisations:
- we can optimize writing  key-value pairs (`{block_hash, block}`, `{account_code_hash, account_code}` etc) when committing raw in-memory cache (simple map of key-value pairs) by using batch updates
- instead of updating permanent trie by traversing Merkle Trie we can insert data from in-memory-trie by fetching all key-value pairs from ets table 
Resolves https://github.com/mana-ethereum/mana/issues/559 https://github.com/mana-ethereum/mana/issues/538
=> Storage optimisations

apps/evm/lib/evm/exec_env.ex, apps/evm/lib/evm/functions.ex, apps/evm/lib/evm/machine_code.ex, apps/evm/lib/evm/machine_state.ex, apps/evm/lib/evm/vm.ex
Before we would calculate `valid_jump_destinations` on every call to
`valid_jump_dest?`. Now we calculate it once ahead of time.
=>  Precompute `valid_jump_destinations`

README.md, apps/blockchain/lib/blockchain/account/repo.ex, apps/blockchain/test/blockchain/state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/account_repo.ex
We should reset storage for newly created accounts. We were
resetting them in the evm cache but we were reading initial values
from the permanent storage. We should read them from the cache
fixes https://github.com/mana-ethereum/mana/issues/575 https://github.com/mana-ethereum/mana/issues/534
related https://gist.github.com/holiman/0154f00d5fcec5f89e85894cbb46fcb2
=> fix initial storage value for EIP1283 sstore gas cost

.circleci/config.yml, apps/evm/mix.exs, apps/evm/test/evm_test.exs, apps/evm/test/support/evm_test_runner.ex
Why:
We would like to start profiling our evm code to look for areas where we
can improve performance. [Parity] has a [benchmark script] for
outputting how long each of the evm common_tests take to run
[Parity]: https://github.com/paritytech/parity-ethereum
[benchmark script]: https://github.com/paritytech/parity-ethereum/blob/f6dcca3ebb6341049b8fc4c890a463277c493bc4/scripts/evm_jsontests_bench.sh
This PR:
Extracts EvmTestRunner. This allows us to run the following type of code
for profiling:
```
% cd apps/evm
% MIX_ENV=test iex -S mix
iex(1)> test_json =
...(1)> File.read!("../../ethereum_common_tests/VMTests/vmPerformance/ackermann31.json") |>
...(1)> Jason.decode!() |>
...(1)> Map.get("ackermann31")
iex(2)> :fprof.apply(EvmTestRunner, :run, [test_json])
iex(3)> :fprof.profile
iex(4)> …
```
=> Extract EvmTestRunner to run common_tests

apps/evm/lib/evm/operation.ex
Why:
Currently, group_to_module is concatenating two strings and turning the
result into an atom to get from an atom to a module. Profiling reveals
that we do this a lot in the course of running code on the EVM.
This PR:
Switches to use pattern matching from known atoms to their corresponding
modules. As a benchmarking example, this takes the fibonacci16
performance test from the common tests from 34_000 milliseconds to
28_000 milliseconds.
=> Switch group_to_module to pattern match

.tool-versions, apps/blockchain/mix.exs, apps/evm/lib/evm/builtin/mod_exp.ex, apps/evm/test/evm/builtin/mod_exp_test.exs
wrong highest bit calculation caused wrong gas cost.
Because of that we were failing `ropsten` chain syncing on block #2_444_903
fixes https://github.com/mana-ethereum/mana/issues/580
=> fix highest bit calculation for exp_mod builtin

.circleci/config.yml, apps/ex_wire/lib/ex_wire/config.ex, apps/ex_wire/lib/ex_wire/handler.ex, apps/ex_wire/lib/ex_wire/kademlia/routing_table.ex, apps/ex_wire/lib/ex_wire/kademlia/server.ex, apps/ex_wire/lib/ex_wire/node_discovery_supervisor.ex, apps/ex_wire/lib/ex_wire/p2p/manager.ex, apps/ex_wire/test/integration/dev_p2p_communication_test.exs, apps/ex_wire/test/integration/node_discovery_test.exs, apps/ex_wire/test/integration/remote_connection_test.exs, apps/ex_wire/test/support/ex_wire/test_helper.ex
This patch fixes our network tests. The goal is to make sure the tests run well against local peers or the bootnodes from the chains. We also make sure the network tests can be run locally or in CircleCI. Though, we opt not to run the tests in CI (this can be changed by making a branch name that ends in "network"). The fixes include:
1. Allowing an external IP address to be specified to give a remote node a real peer id with an IP address that is not 127.0.0.1.
2. Fix a discovery test that initiates find neighbours and checks that we've sent pings. We opt to ignore the pong responses as a simple way of tracking which nodes we've contracted so far.
3. We don't run remote connection tests asynchronously, since it meant we sent multiple connection attempts simultaneously to the same peer.
4. …
=> Fix Network Tests

apps/ex_wire/lib/ex_wire/handshake.ex, apps/ex_wire/lib/ex_wire/p2p/manager.ex, apps/ex_wire/lib/ex_wire/p2p/server.ex, apps/ex_wire/test/ex_wire/handshake_test.exs
When we receive an EIP-8 frame, the packet specifies a size for the EIP-8 header data, but may contain more data that is unrelated to the EIP-8 data. We previously included the extra packet data as the pre-warm for the ingress header, that caused packets like this to break our handshake mechanism (or more correctly, break the next inbound packet). We now correctly set the ingress mac and queue the rest of the data as we await the next packet. This fixes an issue where Parity connections would often fail.
=> Queue Extra Data from EIP-8 Frame

apps/ex_wire/lib/ex_wire/config.ex, apps/ex_wire/lib/ex_wire/peer_supervisor.ex, apps/ex_wire/lib/ex_wire/sync.ex
This patch starts getting our syncing code smarter about what peers it's connected to and why. We allow a user to specify bootnodes from the command line, and we check to see if we're connected to any nodes before we request new blocks. If we haven't yet connected, we'll wait and retry. This logic will grow as we start to run nodes that are consistently connected to 10-25 peers.
=> Start to be smarter about bootnodes and syncing

apps/ex_wire/lib/ex_wire/struct/peer.ex, apps/ex_wire/lib/ex_wire/tcp.ex
This patch allows us to support peers with IPv6 addresses. Erlang has good tools on parsing addresses, though not as much as determining if this might be an address, so when we parse a peer node, we first try it as an IP address, and if that fails, we return it as a charlist (domain name). This allows us to connect to peers with IPv6 addresses, which, for instance, is the enode address when you run `geth --nat none`.
=> Support IPv6 Addresses

apps/ex_wire/README.md, apps/ex_wire/config/dev.exs, apps/ex_wire/lib/ex_wire.ex, apps/ex_wire/lib/ex_wire/config.ex, apps/ex_wire/lib/ex_wire/kademlia/discovery.ex, apps/ex_wire/lib/ex_wire/kademlia/node.ex, apps/ex_wire/lib/ex_wire/p2p/manager.ex, apps/ex_wire/lib/ex_wire/p2p/server.ex, apps/ex_wire/lib/ex_wire/peer_supervisor.ex, apps/ex_wire/lib/ex_wire/struct/peer.ex, apps/ex_wire/lib/ex_wire/sync.ex
This patch begins to connect peer discovery to peer to peer connections. This is pretty early going, but I believe it's an important step in the right direction.
A few comments on this PR.
1. If discovery is disabled, we simply connect to the bootnodes.
2. Otherwise, we don't connect to the bootnodes, and instead we ask them for peers. We try to connect to each of those peers.
a. We should probably keep track of those peers and then choose to connect to individual peers based maybe on distance?
3. When we connect to peers, we try to keep 10 active peers connected (though peers often drop us before we reach this limit).
a. We currently maintain the count by just connecting to new nodes. We should change this to keep track of a set of available nodes and use more intelligent logic when to …
=> Connect Discovery to Peer-to-Peer

apps/ex_wire/lib/ex_wire/peer_supervisor.ex, apps/ex_wire/lib/ex_wire/sync.ex, apps/ex_wire/test/integration/dev_p2p_communication_test.exs
This patch fixes peer sync (syncing against a single node). Previously, once we pulled 100 blocks, we would just stop and do nothing. Now, we correctly continue syncing whenever we have no blocks queued up. While we should be smarter about which blocks to sync and when to ask for more and from which peers, we'll probably end up switching to fast or warp sync before long, which might render this moot. With this patch, syncing against a local parity node works very well (and so does geth before it drops us for not having fast sync enabled).
=> Fix Peer Sync

README.md, apps/blockchain/lib/blockchain/account.ex, apps/blockchain/lib/blockchain/account/repo.ex, apps/blockchain/lib/eth_common_test/state_test_runner.ex, apps/blockchain/scripts/evm_runner.ex, apps/blockchain/test/blockchain/blockchain_state_test.exs, apps/blockchain/test/blockchain_test.exs, apps/evm/lib/evm/operation/environmental_information.ex
Changes: 
- fix `excodehash` op code for empty accounts (fixes https://github.com/mana-ethereum/mana/issues/656)
- update ethereum common tests submodule (https://github.com/ethereum/tests/pull/552)
=> fix extcodehash common test

apps/jsonrpc2/config/config.exs, apps/jsonrpc2/config/test.exs, apps/jsonrpc2/lib/jsonrpc2.ex, apps/jsonrpc2/lib/jsonrpc2/servers/websocket_http.ex, apps/jsonrpc2/mix.exs, apps/jsonrpc2/test/jsonrpc2/http_test.exs, apps/jsonrpc2/test/jsonrpc2/websocket_test.exs
This is matching Parity and Geth functionality where they allow passing binding interface from the CLI.
```
--jsonrpc-port=[PORT]
Specify the port portion of the HTTP JSON-RPC API server. (default: 8545)
--jsonrpc-interface=[IP]
Specify the hostname portion of the HTTP JSON-RPC API server, IP should be an interface's IP address, or all
(all interfaces) or local. (default: local)
--ws-port=[PORT]
Specify the port portion of the WebSockets JSON-RPC server. (default: 8546)
--ws-interface=[IP]
Specify the hostname portion of the WebSockets JSON-RPC server, IP should be an interface's IP address, or all
(all interfaces) or local. (default: local)
```
=> get supervision tree based on http and ws configuration

apps/blockchain/lib/blockchain/ethash.ex, apps/blockchain/test/blockchain/ethash_test.exs
Implements part of #541 
Why:
We would like to be able to verify the results given by other nodes when
adding a new block that the required work had been done to do so.
This PR:
Implements the Proof-of-work algorithm described in Appendix J of the
yellow paper (Byzantium edition).
Note: We've only implemented the full version and have added a pending
test for the light version. This will be implemented in a follow up PR.
=> Add proof-of-work algorithm

apps/blockchain/lib/blockchain/ethash.ex, apps/blockchain/test/blockchain/ethash_test.exs
This relates to #541
Description
===========
Adds the light version of the Proof-of-work Ethash function.
This version uses an in-memory cache version for data aggregation instead of the full dataset.
Note: We extract the common functionality of `Ethash.pow_full` and `Ethash.pow_light` into a private `pow` function.
Wiki description
----------------
We closely follow the implementation outlined in the [wiki](https://github.com/ethereum/wiki/wiki/Ethash#main-loop), so I include a copy of it here for convenience.
=> Adds pow_light function to Ethash

apps/blockchain/lib/blockchain/ethash.ex, apps/blockchain/lib/blockchain/ethash/rand_memo_hash.ex
This is part of #541 
Why?
===
When attempting to run the ethereum common tests for the Ethash PoW, it became apparent that the cache generation is slow.
Note: the tests are not included in this commit because they are not yet passing since they take too long.
What?
=====
This commit includes two optimizations:
1. The initial cache generation (based on a seed hash) recurses N times, and each element is the Keccak 512 of the previous element. Previous to this commit, we were starting with the first element and going to element N, without keeping an accumulated list of elements. So element N would generate all previous elements only for its own calculation. Now we simply keep the values so that we only run through the initial cache generation step N times. (where N is …
=> Optimize Ethash cache generation in two places

.circleci/config.yml
* Removes the env cache (it was not being saved anywhere, so would either always be missing or
always out of date).
* Only caches `deps` based on the `mix.lock` checksum.
* Stops caching `_build` between builds, just pass it between jobs using `persist_to_workspace`.
=> Adjust CircleCI caching

apps/merkle_patricia_tree/lib/merkle_patricia_tree/caching_trie.ex, apps/merkle_patricia_tree/test/merkle_patricia_tree/caching_trie_test.exs
We weren't updating root hash of permanent storage after committing in-memory trie
=> set disk trie root hash from in-memory trie after commit

apps/evm/lib/evm/message_call.ex, apps/evm/test/evm/message_call_test.exs
We weren't considering `out_size` parameter when writing output from reverted message call. `out_size` defines output size that should be written to memory
fixes https://github.com/mana-ethereum/mana/issues/668
=> truncate output for reverted message calls

apps/merkle_patricia_tree/lib/merkle_patricia_tree/caching_trie.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/db.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/db/ets.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/db/rocksdb.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie.ex, apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie_storage.ex, apps/merkle_patricia_tree/mix.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree/caching_trie_test.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree/db/ets_test.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree/db/rocksdb_test.exs, apps/merkle_patricia_tree/test/merkle_patricia_tree/trie_test.exs
Previously, when we had a large number of updates, we would send them all to the NIF at once. For a several megabyte update (which is common in warp sync), this would effectively crash the erlang runtime system (since NIF cannot be pre-empted). This patch changes the system to instead stream the updates in batches. The allows us to play nice with pre-emption, allows for faster and smaller garbage collection and keeps the overall memory footprint significantly lower.
=> Stream Batch Updates for Trie

.circleci/config.yml, apps/blockchain/lib/blockchain/ethash.ex, apps/blockchain/lib/blockchain/ethash/rand_memo_hash.ex, apps/blockchain/test/blockchain/ethash_test.exs
This closes https://github.com/mana-ethereum/mana/issues/541
Description
===========
This commit fixes a few issues that we encountered with the Ethash implementation. The issues were raised when trying to pass the PoW Ethereum common tests.
Some of the issues fixed:
- Use 32 bit unsigned integer in RandMemoHash algorithm (generates correct cache)
- Use correct 32 bit unsigned integer in mix initialization
Testing
-------
Note that we only test the light version of the ethash algorithm. The full version simply generates the full dataset prior to calculating the algorithm. The light version lazily generates the dataset items it requires.
We only test the light version because of time constraints. The dataset generation for the PoW common tests takes a long time, so we do not want to …
=> Complete Ethash implementation

apps/ex_wire/config/config.exs, apps/ex_wire/config/test.exs, apps/ex_wire/lib/ex_wire/handler.ex, apps/ex_wire/lib/ex_wire/handler/find_neighbours.ex, apps/ex_wire/lib/ex_wire/handler/neighbours.ex, apps/ex_wire/lib/ex_wire/handler/ping.ex, apps/ex_wire/lib/ex_wire/handler/pong.ex, apps/ex_wire/lib/ex_wire/kademlia.ex, apps/ex_wire/lib/ex_wire/kademlia/server.ex, apps/ex_wire/lib/ex_wire/network.ex, apps/ex_wire/lib/ex_wire/node_discovery_supervisor.ex, apps/ex_wire/test/ex_wire/ex_wire_test.exs, apps/ex_wire/test/ex_wire/handler/find_neighbours_test.exs, apps/ex_wire/test/ex_wire/kademlia_test.exs, apps/ex_wire/test/support/ex_wire/adapter/test.ex
- Removing configurable process names (?).
- Spreading process state over modules.
- Removed keyword type server name passing
An alternative to #680
=> Peer mngmt - 2

apps/ex_wire/lib/ex_wire/dev_p2p.ex, apps/ex_wire/lib/ex_wire/packet/capability/eth.ex, apps/ex_wire/lib/ex_wire/packet/capability/mana.ex, apps/ex_wire/lib/ex_wire/packet/protocol/hello.ex
Fixes an issue where we blindly pull our capabilities list from config, instead starting with the capabilities that we _can_ support and paring them down based on what is configured.
Also adds logic to `ExWire.Packet.Capability.Eth.Hello` to only recommend activating peers if they have shared capabilities.
=> Wire Sub-Protocol Capability Configuration

apps/blockchain/lib/blockchain/block.ex
The Block struct contains information about a block, and the block hash is a very important and commonly used field. However, as it's based on the other data in a block (which may have been added peicemeal), it's not obvious when we should calculate the blockhash (though it's very obvious when we need it). This makes block_hash a good candidate for lazy evaluation (calculate the value when it's needed, but keep it around for later uses). We standardize this by adding two functions `Block.with_hash` and `Block.fetch_block_hash` which handle reading the block hash if it exists and calculating it if it doesn't. As Elixir values are immutable, we don't have a good way of forcing downstream code to continue to pass around the struct with the calculated value, but we can try our best that it …
=> Add Block `with_hash` and `fetch_block_hash` helpers

apps/evm/lib/evm/builtin/mod_exp.ex, apps/evm/test/evm/builtin/mod_exp_test.exs
Most languages (Rust, Java etc) have builtin functions that calculate leading zeroes. Unfortunately Elixir doesn't have them. So we're using what we have.
we need to pad 32-byte numbers with zeroes in its binary representation.
fixes https://github.com/mana-ethereum/mana/issues/696
=> count bits only for 256 bit numbers

apps/blockchain/lib/blockchain/block.ex
while working on https://github.com/mana-ethereum/mana/pull/677 I found that block hash keys are generated with `}` at the end
Example
`"hash_for_1}"`
=> fix block hash key

apps/ex_wire/config/dev.exs, apps/ex_wire/lib/ex_wire/connection_observer.ex, apps/ex_wire/lib/ex_wire/dev_p2p.ex, apps/ex_wire/lib/ex_wire/p2p/manager.ex, apps/ex_wire/lib/ex_wire/packet.ex, apps/ex_wire/lib/ex_wire/packet/protocol/hello.ex, apps/ex_wire/lib/ex_wire/struct/peer.ex, apps/ex_wire/test/ex_wire/dev_p2p_test.exs, apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
This expand a Peer struct with p2p_version and caps. 1. Setup for rating and 2. Both Parity and Geth support JSONRPC admin methods where caps is returned for connected peers. 
My next step in the works is to create a separate struct that will have Peer + other related fields that will help us maintain Peers rating, but related just to ratings.
=> getting p2p version and caps into the peer

apps/jsonrpc2/lib/bridge/sync.ex, apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex, apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs, apps/jsonrpc2/test/support/bridge_sync_mock.ex
Changes:
- Implement `eth_getTransactionByBlockNumberAndIndex` JSON RPC method
- Implement `eth_getTransactionByBlockHashAndIndex` JSON RPC method
part of https://github.com/mana-ethereum/mana/issues/675
=> add transaction getter methods for JSON RPC API

apps/blockchain/lib/blockchain/block.ex, apps/blockchain/test/blockchain/block_test.exs, apps/jsonrpc2/lib/bridge/sync.ex, apps/jsonrpc2/lib/jsonrpc2/response/receipt.ex, apps/jsonrpc2/lib/jsonrpc2/response/transaction.ex, apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex, apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs, apps/jsonrpc2/test/jsonrpc2/response/receipt_test.exs, apps/jsonrpc2/test/support/bridge_sync_mock.ex, apps/jsonrpc2/test/support/test_factory.ex
Changes:
- Implement `eth_getTransactionReceipt` 
Next PRs:
- encode logs
- encode created contract address for contract creation transactions
=> fetch receipt from database for JSON RPC

apps/blockchain/lib/blockchain/block.ex, apps/jsonrpc2/lib/bridge/sync.ex, apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex, apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs, apps/jsonrpc2/test/support/bridge_sync_mock.ex
Changes:
- implement `eth_getUncleByBlockHashAndIndex`
- implement `eth_getUncleByBlockIndexAndIndex`
=> Uncle getter methods for JSON RPC API

apps/cli/lib/block_provider/rpc.ex
Currently, the sync is failing when a block is not found using RPC client
```
(BadMapError) expected a map, got: nil  
(elixir) lib/map.ex:437: Map.get(nil, "hash", nil)
lib/block_provider/rpc.ex:185: CLI.BlockProvider.RPC.get/4
lib/block_provider/rpc.ex:71: CLI.BlockProvider.RPC.get_block/2
lib/sync.ex:45: CLI.Sync.sync_new_blocks/8
```
=> handle not found blocks in RPC client
