mana-ethereum/mana

- github-labels.json
config file to generate repo labels with https://github.com/himynameisdave/git-labelmaker
> Add super-important file with github labels

- .circleci/config.yml
- apps/ex_wire/config/dev.exs
- apps/merkle_patricia_tree/lib/db/ets.ex
- apps/merkle_patricia_tree/lib/hex_prefix.ex
- apps/merkle_patricia_tree/lib/list_helper.ex
- apps/merkle_patricia_tree/lib/trie.ex
- apps/merkle_patricia_tree/lib/trie/builder.ex
- apps/merkle_patricia_tree/lib/trie/destroyer.ex
- apps/merkle_patricia_tree/lib/trie/helper.ex
- apps/merkle_patricia_tree/lib/trie/inspector.ex
- apps/merkle_patricia_tree/lib/trie/node.ex
- apps/merkle_patricia_tree/lib/trie/storage.ex
- apps/merkle_patricia_tree/mix.exs
- apps/merkle_patricia_tree/test/hex_prefix_test.exs
- apps/merkle_patricia_tree/test/merkle_patricia_tree_test.exs
- apps/merkle_patricia_tree/test/support/node_helpers.ex
- apps/merkle_patricia_tree/test/test_helper.exs
- apps/merkle_patricia_tree/test/trie/inspector_test.exs
- apps/merkle_patricia_tree/test/trie_test.exs
This PR:
* Resolves TODOs in MMPT app 
* Adds more tests
* Adds comments with more or less detailed explanation of how things work under the hood
* Excludes tests with `:pending` tag
* Disables blockhain `sync` in dev env
* Applies some random refactoring
resolves #25
> Merkle-Patricia Tree enhancements

- apps/blockchain/lib/bit_helper.ex
- apps/blockchain/lib/blockchain/account.ex
- apps/blockchain/lib/blockchain/block.ex
- apps/blockchain/lib/blockchain/bloom.ex
- apps/blockchain/lib/blockchain/contract.ex
- apps/blockchain/lib/blockchain/transaction.ex
- apps/blockchain/lib/blockchain/transaction/signature.ex
- apps/blockchain/mix.exs
- apps/blockchain/test/blockchain/account_test.exs
- apps/blockchain/test/blockchain/block_test.exs
- apps/blockchain/test/blockchain/state_test.exs
- apps/blockchain/test/blockchain/transaction_test.exs
- apps/blockchain/test/blockchain_test.exs
- apps/exth_crypto/lib/hash/keccak.ex
> Chore/use exth crypto#35

- apps/blockchain/lib/blockchain/block.ex
- apps/blockchain/lib/eth_common_test/helpers.ex
- apps/evm/lib/block/header.ex
Fixes some of the dialyzer warnings for the Blockchain app.
Warning fixed is included in each commit message.
> Dialyzer warning fixes #2

- apps/blockchain/lib/blockchain/account.ex
- apps/blockchain/lib/blockchain/block.ex
- apps/blockchain/lib/blockchain/blocktree.ex
- apps/blockchain/lib/blockchain/interface/account_interface.ex
- apps/blockchain/lib/blockchain/transaction.ex
Fixes `Unknown type` warnings in Blockchain app.
> Dialyzer warning fixes #3

- apps/evm/lib/evm/builtin.ex
Just passes though the data object and returns it as the output.
> Precompiled Contract: Identity

- apps/evm/lib/evm/builtin.ex
Implements a precompiled contract that recovers a public key from a signed hash
(Elliptic curve digital signature algorithm public key recovery function)
Uses fixed gas amount.
> Precompiled Contract: ecrec

- apps/evm/lib/evm/functions.ex
- apps/evm/lib/evm/machine_code.ex
- apps/evm/lib/evm/operation.ex
- apps/evm/lib/evm/operation/metadata/system.ex
resolves https://github.com/poanetwork/mana/issues/130
> add invalid operation

- apps/evm/lib/evm/gas.ex
- apps/evm/lib/evm/operation/metadata/system.ex
- apps/evm/lib/evm/operation/system.ex
resolves https://github.com/poanetwork/mana/issues/128
> Static call op

- apps/evm/lib/evm/debugger.ex
> Fix Debugger memory contents inspection

- apps/blockchain/lib/blockchain/chain.ex
> Resolve the chain spec json file relative to the file reading it

- apps/blockchain/test/blockchain/state_test.exs
- apps/evm/lib/evm/message_call.ex
- apps/evm/lib/evm/operation/system.ex
Resolves https://github.com/poanetwork/mana/issues/185
The problem was caused by the wrong active words count after call operation
> increment words count for call operation

- apps/blockchain/lib/blockchain/account.ex
- apps/blockchain/lib/blockchain/contract/create_contract.ex
- apps/blockchain/test/blockchain/state_test.exs
- apps/evm/lib/evm/gas.ex
- apps/evm/lib/evm/operation/system.ex
- apps/evm/lib/evm/vm.ex
Changes 
- check if account exists before creating it
> fix new account hash collisions

- apps/blockchain/test/blockchain/state_test.exs
- apps/evm/lib/evm/operation/environmental_information.ex
Changes:
- We shouldn't pad data that we want to write with zeroes
Fixes https://github.com/poanetwork/mana/issues/201
> fix reading memory with offset

- .gitignore
- apps/blockchain/config/config.exs
- apps/blockchain/config/test.exs
- apps/blockchain/scripts/sync_with_infura.ex
This will allow us to save our state state so we won't need to re-sync
every time we run the script.
> Closes #236: Use rocksdb when syncing with Infura

- apps/blockchain/scripts/generate_state_tests.ex
- apps/blockchain/test/blockchain/state_test.exs
- apps/blockchain/test/blockchain_test.exs
- apps/evm/lib/evm/interface/mock/mock_account_interface.ex
- apps/evm/lib/evm/message_call.ex
- apps/evm/lib/evm/operation/system.ex
- apps/evm/lib/evm/refunds.ex
- apps/evm/lib/evm/sub_state.ex
- apps/evm/test/evm/operation/system_test.exs
Nested operations (message calls and contract creations) did not save execution sub states
Resolves https://github.com/poanetwork/mana/issues/153
Fixes https://github.com/poanetwork/mana/issues/239
> Merge nested sub states

- apps/blockchain/lib/blockchain/contract/create_contract.ex
- apps/blockchain/test/blockchain/state_test.exs
- apps/blockchain/test/blockchain_test.exs
fixes https://github.com/poanetwork/mana/issues/245
> fix revertprefound test

- apps/blockchain/lib/blockchain/transaction.ex
- apps/blockchain/scripts/generate_state_tests.ex
- apps/blockchain/test/blockchain/block_test.exs
- apps/blockchain/test/blockchain/state_test.exs
- apps/blockchain/test/blockchain/transaction_test.exs
fixes https://github.com/poanetwork/mana/issues/249
> fix createNameRegistratorPerTxsAfter test

- apps/blockchain/test/blockchain/state_test.exs
- apps/evm/lib/evm/message_call.ex
- apps/evm/lib/evm/sub_state.ex
- apps/evm/test/evm_test.exs
Changes:
- Append log entry to the beginning of the log list
- Deduplicate logs when merging substates
fixes https://github.com/poanetwork/mana/issues/262
> fix recursive-bomb-log2 test

- apps/blockchain/scripts/generate_state_tests.ex
- apps/blockchain/test/blockchain/state_test.exs
- apps/evm/lib/evm/sub_state.ex
Changes:
- Fix state tests generation script
- Do not deduplicate logs when merging sub states
> fix stSystemOperationsTest/CallRecursiveBombLog test

- apps/blockchain/lib/blockchain/block.ex
- apps/blockchain/lib/blockchain/blocktree.ex
- apps/blockchain/scripts/generate_blockchain_tests.ex
- apps/blockchain/test/blockchain_test.exs
Some genesis blocks in tests have hashes in json tests that don't correspond to their headers.
fixes https://github.com/poanetwork/mana/issues/274
> do not calculate blockhash for genesis blocks in tests

- apps/blockchain/test/blockchain/state_test.exs
- apps/blockchain/test/blockchain_test.exs
- apps/evm/lib/helpers.ex
fixes https://github.com/poanetwork/mana/issues/291
> fix signed operations helper

- apps/blockchain/lib/blockchain/blocktree.ex
- apps/blockchain/scripts/generate_blockchain_tests.ex
- apps/blockchain/test/blockchain_test.exs
fixes https://github.com/poanetwork/mana/issues/300
fixes https://github.com/poanetwork/mana/issues/302
> fix choosing best block

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- apps/blockchain/scripts/sync_with_infura.ex
I made some basic changes to enhance the Readme and added a Contributing and Code of Conduct file. Also fixed a typo in the sync_with_infura script. 
I will add some additional info about the Umbrella project structure next and potentially info about keccack and other technical details.  Let me know what else you'd like to see.
A couple of questions:
1. Is it just the Mana project, or Exthereum Mana
2. In the contributing file are there other considerations you would like to add? Should contributors run mix credo for example before submitting a pr, or any other specifics that would make your lives easier?
> Documentation updates

- apps/evm/lib/evm/operation/environmental_information.ex
- apps/evm/lib/evm/operation/stop_and_arithmetic.ex
- apps/evm/lib/math_helper.ex
- apps/evm/mix.exs
- apps/evm/test/math_helper_test.exs
- mix.lock
fixes "stRandom2/randomStatetest545" of homestead tests
> use decimal library for arithmetic

- .dialyzer.ignore-warnings
- .tool-versions
- README.md
- apps/blockchain/lib/blockchain/contract/create_contract.ex
- apps/blockchain/lib/blockchain/contract/message_call.ex
- apps/blockchain/test/blockchain/state_test.exs
- apps/blockchain/test/blockchain_test.exs
- apps/evm/lib/evm/exec_env.ex
- apps/evm/lib/evm/functions.ex
- apps/evm/lib/evm/gas.ex
- apps/evm/lib/evm/message_call.ex
- apps/evm/test/evm_test.exs
For suicides of not existing accounts, we should charge additional gas
> fix gas cost for suicide operations (EIP150)

- apps/blockchain/scripts/sync_with_infura.ex
Before we were only saving the state when validation failed. This was
fine early on when failures were more common but now validation errors
are few and father between. Now we save state periodically so if the
task fails due to a catastrophic failure (such as a memory overflow) we
won't have to resync.
> Save state every 1000 blocks in SyncWithInfura

- .dialyzer.ignore-warnings
- apps/blockchain/lib/blockchain/block.ex
- apps/blockchain/lib/blockchain/contract/create_contract.ex
- apps/blockchain/lib/blockchain/interface/account_interface.ex
- apps/blockchain/lib/blockchain/interface/account_interface/cache.ex
- apps/blockchain/lib/blockchain/transaction.ex
- apps/blockchain/test/blockchain/interface/account_interface/cache_test.exs
- apps/blockchain/test/blockchain/interface/account_interface_test.exs
- apps/blockchain/test/blockchain/transaction_test.exs
- apps/blockchain/test/support/state_test_runner.ex
Changes:
- Work with cache throughout transaction execution
- Start transaction count with zero when storing transaction
> work with cache when adding blocks

- .dialyzer.ignore-warnings
- apps/blockchain/lib/blockchain/block.ex
- apps/blockchain/lib/blockchain/block/holistic_validity.ex
- apps/blockchain/lib/blockchain/transaction/receipt/bloom.ex
- apps/evm/lib/evm/builtin/ecrec.ex
- apps/evm/lib/evm/message_call.ex
Resolves https://github.com/poanetwork/mana/issues/487
> logs bloom validation

- apps/evm/lib/evm/operation/environmental_information.ex
- apps/evm/test/evm/operation/environmental_information_test.exs
fixes https://github.com/poanetwork/mana/issues/502
We should validate params for `codecopy`
> fix codecopy

- apps/evm/lib/evm/gas.ex
fixes https://github.com/poanetwork/mana/issues/513
> fix call gas cost

- apps/blockchain/scripts/sync_with_infura.ex
Description
===========
We have been saving both a "current_block_hash" and "current_block_tree" in the database every 1000 blocks. The problem comes when a failure occurs at a block that is a multiple of 1000. In that case, it appears as though we have a corrupted db, but in reality all that has happened is that we saved a "current_block_hash" too early (before actually validating the block), and next time we search for that block in our database, it cannot be found.
So we do two things here to improve that,
1. We derive the current block hash from the current block tree. Since the tree has the best block in it, that is all we need.
2. We move the saving of the current block tree to after we have verified and added the block (instead of before). That way, when we try to run the script …
> Derive current block from tree in sync_with_infura

- README.md
- apps/blockchain/test/blockchain/state_test.exs
- apps/blockchain/test/blockchain_test.exs
- apps/evm/lib/evm/gas.ex
we weren't substracting memory cost for returndatacopy
> fix returndatacopy cost

- .dialyzer.ignore-warnings
- apps/blockchain/lib/blockchain/block.ex
- apps/blockchain/lib/blockchain/block/holistic_validity.ex
- apps/blockchain/lib/blockchain/block_header_info.ex
- apps/blockchain/lib/blockchain/blocktree.ex
- apps/blockchain/lib/blockchain/genesis.ex
- apps/blockchain/lib/eth_common_test/blockchain_test_runner.ex
- apps/blockchain/test/blockchain/block_header_info_test.exs
- apps/blockchain/test/blockchain/block_test.exs
- apps/blockchain/test/blockchain/blocktree_test.exs
- apps/cli/lib/cli.ex
- apps/cli/lib/sync.ex
- apps/cli/test/sync_test.exs
- apps/ex_wire/lib/ex_wire/struct/block_queue.ex
- apps/merkle_patricia_tree/lib/merkle_patricia_tree/caching_trie.ex
- apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie.ex
- apps/merkle_patricia_tree/lib/merkle_patricia_tree/trie_storage.ex
This PR replaces `Trie` with `CachingTrie` in the `cli` project. Now the state is committed after  `n` blocks
> cache sync

- .circleci/config.yml
- .tool-versions
- README.md
- bin/setup
- mix.exs
The latest version of elixir is 1.7.4 but it's not available on circle ci
> upgrade elixir version to 1.7.3

- apps/blockchain/test/blockchain/transaction_test.exs
- apps/evm/lib/evm/functions.ex
- apps/evm/lib/evm/gas.ex
- apps/evm/lib/evm/machine_state.ex
- apps/evm/lib/evm/vm.ex
resolves https://github.com/mana-ethereum/mana/issues/570
> calculate gas cost only once

- .circleci/config.yml
remove rust installation from ci because we don't use it anymore
> remove rust installation from ci

- README.md
new EXTCODEHASH tests were added
https://github.com/ethereum/tests/pull/542
> update ethereum common tests

- .circleci/config.yml
- apps/cli/mix.exs
- mix.lock
https://github.com/henrik/progress_bar/pull/21
Also, fixes Byzantium tests timeout
> upgrade progress_bar

- README.md
https://github.com/ethereum/tests/pull/548
> update ethereum common tests submodule

- apps/blockchain/lib/blockchain/chain.ex
- apps/blockchain/scripts/generate_blockchain_tests.ex
- apps/blockchain/test/blockchain_test.exs
- chains/byzantium_to_constantinople_transition_test.json
https://github.com/ethereum/tests/pull/547
> add Byzantium to Constantinople transition test

- apps/blockchain/lib/blockchain/account.ex
- apps/blockchain/lib/blockchain/account/repo.ex
- apps/blockchain/lib/blockchain/account/repo/cache.ex
- apps/blockchain/lib/blockchain/account/storage.ex
- apps/blockchain/test/blockchain/account/repo/cache_test.exs
- apps/blockchain/test/blockchain/account/repo_test.exs
with https://github.com/mana-ethereum/mana/pull/629 we started committing all code that was read from the database.
But we should commit only code for new accounts.
> do not commit clean account code

- .circleci/config.yml
> flush cache

- apps/blockchain/lib/blockchain/account.ex
- apps/blockchain/lib/blockchain/account/repo/cache.ex
resolves https://github.com/mana-ethereum/mana/issues/617
> optimize storage commits

- apps/blockchain/mix.exs
- apps/evm/mix.exs
- apps/ex_wire/mix.exs
- apps/merkle_patricia_tree/mix.exs
Some leftover cleanup. Also fixed licenses for the apps.
> Clean up some github references

- README.md
https://github.com/ethereum/tests/pull/543
> add new Constantinople extcodehash tests

- apps/evm/lib/evm/builtin/mod_exp.ex
- apps/evm/test/evm/builtin/mod_exp_test.exs
fixes https://github.com/mana-ethereum/mana/issues/687
> fix first bit calculation for small numbers

- .formatter.exs
- .gitignore
- apps/blockchain/mix.exs
- apps/cli/mix.exs
- apps/evm/mix.exs
- apps/ex_wire/mix.exs
- apps/exth/mix.exs
- apps/exth_crypto/mix.exs
- apps/jsonrpc2/mix.exs
- apps/merkle_patricia_tree/mix.exs
- config/config.exs
- mix.exs
- mix.lock
CLI should offer configuration of logger level (TBD in a later PR).
FYI, this logger backend does not support log rotation which is kinda disappointing. If it's a requirement, we should consider Lager.
> log to disk

- README.md
- apps/blockchain/lib/blockchain/account/repo.ex
- apps/blockchain/test/blockchain/blockchain_state_test.exs
- apps/blockchain/test/blockchain_test.exs
resolves https://github.com/mana-ethereum/mana/issues/719
> fix dynamicAccountOverwriteempty test

- README.md
https://github.com/ethereum/tests/pull/568
> add new extcodehash tests

- README.md
https://github.com/ethereum/tests/pull/569
> more extcodehash tests

- apps/blockchain/lib/blockchain/block.ex
- apps/blockchain/lib/blockchain/transaction.ex
- apps/blockchain/test/blockchain/block_test.exs
- apps/jsonrpc2/lib/bridge/sync.ex
- apps/jsonrpc2/lib/jsonrpc2/response/block.ex
- apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
- apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
- apps/jsonrpc2/test/support/bridge_sync_mock.ex
Changes:
- Implement `eth_getTransactionByHash` JSON RPC method
> return transaction by hash

- apps/ex_wire/lib/ex_wire/sync.ex
Removing logic to send an empty GetBlockBodies request when we get an empty `BlockHeaders` response
> Improve Empty BlockHeaders Response Handling

- apps/jsonrpc2/lib/bridge/sync.ex
- apps/jsonrpc2/lib/jsonrpc2/spec_handler.ex
- apps/jsonrpc2/test/jsonrpc2/mana_handler_test.exs
- apps/jsonrpc2/test/support/bridge_sync_mock.ex
Changes: 
- implement `eth_getStorageAt` JSON RPC method
> implement `eth_getStorageAt` JSON RPC method
